### ISSUE TITLE
Weird notification reasons messages

### ISSUE THREAD

**Issue by pdonias** [sindresorhus/notifier-for-github#100]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/notifier-for-github/issues/100)

The notification reasons you chose are a bit weird:

``` js
const reasons = {
    subscribed: 'You are watching the repository',
    manual: 'You are subscribed to this thread',
    author: 'You created this thread',
    comment: 'New comment',
    mention: 'You were mentioned',
    team_mention: 'Your team was mentioned',
    state_change: 'Thread status changed',
    assign: 'You were assigned to the issue',
    default: ''
};
```

For example, the `reason` being `comment` doesn't mean there is a new comment on the thread. It means that you're receiving this notification because you commented on this thread earlier.

https://developer.github.com/v3/activity/notifications/#notification-reasons

And I think it's the same behaviour for `mention` (and I guess the others as well) even though it's not very clear what's intended by "content" in the API documentation. When someone comments a thread, I'm often receiving a notification with the "You were mentioned" message even though I wasn't mentioned in the comment itself but in the thread content.
(This needs to be checked because I'm not sure)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)
### Submitted pull Requests
- [#193 Rewording notification reasons](https://issuehunt.io/r/sindresorhus/notifier-for-github/pull/193)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/notifier-for-github/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by YurySolovyov** [comment]
I'm happy to tweak them, any suggestions?

**Comment by pdonias** [comment]
I don't know since I'm not really sure of the exact behaviour but I guess for the `comment`, you could have something like:
```js
`You commented on this ${notification.subject.type}`
```

I just asked for precisions to the Github support so when they reply, if I have a bit of time, I'll make a pull request :)

**Comment by YurySolovyov** [comment]
Mind posting reply here when it is ready?

**Comment by pdonias** [comment]
Sure

**Comment by pdonias** [comment]
Here's the reply:

> Hey Pierre,

>Thanks for reaching out! You asked:

>>does it mean that the user has been mentioned in the comment that triggered the notification or wherever else in the thread? In other words, what does "the content" mean in this case?

>Great question! In this context, "the content" could mean that you were specifically mentioned in an issue comment, a pull request comment or a commit message.

>I hope that helps, but let us know if you have any other questions!

>All the best,
>Francis

Here, I was just talking about the "mention" value. I wasn't sure to understand yet so I sent a few more e-mails and here's what I understood: `mention` is pretty much an edge case.
Here's why:
- If you were mentioned earlier in an issue and someone posts a comment _without_ mentioning you, you will receive a notification with the `reason` "mention". That means "Something happened in an issue in which you were mentioned earlier".
- But when someone mentions you in a comment, you _also_ receive a notification with the `reason` "mention" because something happened in the issue (the comment) and, as a matter of fact, you _were_ mentioned earlier in this issue, "earlier" being actually "right now" in this case.

So it definitely means that what's inside the `reason` prop is _why_ you are receiving the notification but not what _triggered_ it. I still don't understand the `state_change` though, since it really looks like it's what _triggered_ the notification :/

Anyway, the `comment` message should definitely be modified and the `mention`, `mention_team` and `assign` messages may be reworded since the messages are a bit ambiguous IMHO.

**Comment by sindresorhus** [comment]
PR welcome to improve this.

---

> *Note: This issue has a bounty, so it's expected that you are an experienced programmer and that you give it your best effort if you intend to tackle this. Don't forget, if applicable, to add tests, docs (double-check for typos), and update TypeScript definitions. And don't be sloppy. Review your own diff multiple times and try to find ways to improve and simplify your code. Instead of asking too many questions, present solutions. The point of an issue bounty is to reduce my workload, not give me more. Include a 🦄 in your PR description to indicate that you've read this. Thanks for helping out 🙌* - @sindresorhus

**Comment by notlmn** [comment]
We currently have with issues with error messages too, and I think this issue is closely related to that.

Currently the reasons for most errors are also a bit weird, like "Unknown error", which happens to include any `ERR_NAME_NOT_RESOLVED` or `ERR_CONNECTION_CLOSED` for context (that happen when you are not connected to internet or captive portal logins).

But these errors should be classified as `'server error'` and be considered as "user not connected to internet".

I think we should also address these issues as they are closely related.
