### ISSUE TITLE
Extension has started crashing regularly recently

### ISSUE THREAD

**Issue by zubin** [sindresorhus/notifier-for-github#105]
I've been using this for a few months and it's been great (thank you!).

Unfortunately, it's been crashing regularly recently (maybe the last 2 weeks). 

A Chrome desktop notification usually displays saying that the extension has crashed and to "click to reload". Other than that (which I often miss), there's no indication as to why or when it happens; the icon just disappears. 

I'm on Mac Sierra btw.

**Comment by jacobbearden** [comment]
What version of Chrome are you running?

**Comment by zubin** [comment]
Version 54.0.2840.98 (64-bit)

**Comment by backus** [comment]
It has been crashing for me lately as well. I'm on Version 55.0.2883.95 (64-bit)

**Comment by SEAPUNK** [comment]
Same. I'll try to leave the devtools for the extension open in the background, see if I can catch anything.

**Comment by notlmn** [comment]
This seems to be like a problem in older versions of Chrome handling extensions.

Closing this for now, but feel free to reopen if you still experience the same issue!
