### ISSUE TITLE
When only 1 notification exists, clicking the extension icon should like directly to the notification's URL

### ISSUE THREAD

**Issue by shadowfacts** [sindresorhus/notifier-for-github#107]
So that instead of having to go to the notifications list page and from there go to where the notification originated from, being able to click on the extension to go directly to the URL that the notification originated, saving a bit of time.

**Comment by sodoku** [comment]
I would make that optional, as I often just want to see the notification details, but not necessarily mark it as read.

**Comment by notlmn** [comment]
Closing this in favor of @sodoku's comment. You do not want to automatically mark a notification read.
