### ISSUE TITLE
Show notification in a popup

### ISSUE THREAD

**Issue by math2001** [sindresorhus/notifier-for-github#108]
Hi!

First, thanks for your extension, it's really helpful!

But, I think it would be helpful if you could display the notification in a popup. What do you think about it?

Thanks again,

Matt

**Comment by jacobbearden** [comment]
Could you elaborate more? I'm not entirely sure what you mean.

**Comment by math2001** [comment]
When you click on the icon of the extension, instead of opening a new tab, you show a popup with all the notifications listed.

Here's what I call a popup:

![](https://developer.chrome.com/static/images/gettingstarted-preview.png)

Matt

**Comment by jacobbearden** [comment]
I'm all for this idea, and if any others support it I'll get right on adding it.

// @YurySolovyov @gcochard @fstoerkle

**Comment by math2001** [comment]
Awesome!

**Comment by YurySolovyov** [comment]
We already have desktop notifications, so -1 from me. I'd say it belongs to [refined-github](https://github.com/sindresorhus/refined-github), or nowhere

**Comment by math2001** [comment]
> We already have desktop notifications

The idea is not to replace the desktop notif, just to prevent opening a new tab for listing the notifications. Like this, you just click on the icon, it lists the notificatons, and you can open the whichever one you want. Like this, you don't get any extra tab.

> I'd say it belongs to refined-github

They aren't doing any extension, do they? How could it solve the problem?

**Comment by notlmn** [comment]
@math2001 Good idea but not at all useful for people with a LOT of notifications, then we have to implement filtering, which GH already provides.
