### ISSUE TITLE
"Unknown error" on FF52

### ISSUE THREAD

**Issue by hackel** [sindresorhus/notifier-for-github#113]
I've just installed this extension (from the Chrome store) on Firefox 52.0a2 using Chrome Store Foxified.  I'm assuming this is the best way to do this currently, but let me know if there's a better method.

The notification icon has a red question mark with "Unknown error" in the tooltip.  I get the following output on the browser console when I enable it:
```
15:12:46.156 Warning: attempting to write 11927 bytes to preference extensions.bootstrappedAddons. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
15:12:46.254 1483564366254	addons.webextension.lmjdlojahmbbcodnpecnjnmlddbkjhnn@chrome-store-foxified-694046985	WARN	Loading extension 'lmjdlojahmbbcodnpecnjnmlddbkjhnn@chrome-store-foxified-694046985': Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
15:12:46.257 1483564366257	addons.webextension.lmjdlojahmbbcodnpecnjnmlddbkjhnn@chrome-store-foxified-694046985	WARN	Loading extension 'lmjdlojahmbbcodnpecnjnmlddbkjhnn@chrome-store-foxified-694046985': Reading manifest: Error processing update_url: An unexpected property was found in the WebExtension manifest.
15:12:46.257 1483564366257	addons.webextension.lmjdlojahmbbcodnpecnjnmlddbkjhnn@chrome-store-foxified-694046985	WARN	Loading extension 'lmjdlojahmbbcodnpecnjnmlddbkjhnn@chrome-store-foxified-694046985': Reading manifest: Error processing optional_permissions: An unexpected property was found in the WebExtension manifest.
15:12:46.354 1483564366354	addons.webextension.lmjdlojahmbbcodnpecnjnmlddbkjhnn@chrome-store-foxified-694046985	WARN	Please specify whether you want browser_style or not in your browser_action options.
15:12:46.722 Warning: attempting to write 12187 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
15:12:47.774 TypeError: window.chrome.permissions is undefined[Learn More]  main.js:545:5
15:12:47.841 console.trace(): inspector.js:770
	WalkerFront<.getMutations</< resource://devtools/shared/fronts/inspector.js:770
	Handler.prototype.process resource://gre/modules/Promise-backend.js:932
	this.PromiseWalker.walkerLoop resource://gre/modules/Promise-backend.js:813
```
Firefox's WebExtension support may not support everything yet (though I'm surprised, since quite a few extensions work fine these days).  Just wanted to get this out there.

Thanks to everyone who's continuing to work on this useful addon.

**Comment by PierBover** [comment]
I've been getting the "unknown error" with the red question mark lately too in Chrome.

![image](https://cloud.githubusercontent.com/assets/226483/21970540/3b6a6b42-db75-11e6-86a9-f470e66033f9.png)

I opened the extension in dev mode but the console is empty...

**Comment by oncletom** [comment]
I usually get the _unknown error_ when I open the browser while being offline. It does not seem to later display an updated issues count unless I click on the extension icon.

Is that your use case too?

**Comment by PierBover** [comment]
> I usually get the unknown error when I open the browser while being offline. It does not seem to later display an updated issues count unless I click on the extension icon.

I'm not sure about opening the browser in offline mode, but the red question mark icon disappears after clicking to see the notifications on Github.

**Comment by Equinox** [comment]
I'm experiencing the same as above -- the unknown error with the red question mark (using Chrome beta, but pretty sure it was there while using the stable channel also) which seems to return to expected behaviour once clicked.
