### ISSUE TITLE
Two tabs are opened unless current tab is empty

### ISSUE THREAD

**Issue by shadowfacts** [sindresorhus/notifier-for-github#114]
Clicking the Notifier extension icon the top bar results in two tabs, both on the Notifications page, opening _unless_ the current tab is empty (at the new-tab page).

![ghnotifier](https://cloud.githubusercontent.com/assets/7091588/21828888/10625ff8-d761-11e6-9e92-969b42e92b71.gif)

**Comment by notlmn** [comment]
This should be fixed at some point, but please do reopen if you still see this!
