### ISSUE TITLE
I'm getting notifications numbers on the icon when there are no notifications

### ISSUE THREAD

**Issue by shawnwildermuth** [sindresorhus/notifier-for-github#117]
Maybe I registered it wrong. Is the URL supposed to link to my account, or is that the API Key for?  Could be me, but I don't think so.

**Comment by not-an-aardvark** [comment]
The API token is specific to an account. It might not be the same as the account that you're logged into on the browser. You could try regenerating the token from the correct account and seeing if it fixes the problem.

**Comment by notlmn** [comment]
Either this is an issue with the extension not querying the endpoint after you have read all your notifications (due to the delay, which is by design), or you may have configured with a different accounts API token.
