### ISSUE TITLE
Use Notifications API to get desktop notifications

### ISSUE THREAD

**Issue by johanbrook** [sindresorhus/notifier-for-github#12]
Hi! Great extension, I love it!

I currently have email notifications activated for _everything_ on GitHub, since I can't miss out on stuff. The notifications icon in this extension is a bit too unobtrusive – would it be possible to support opt-in desktop notifications for GitHub?

Thanks!

**Comment by inikulin** [comment]
+1

**Comment by YuriSolovyov** [comment]
I did another try in #66, any feedback welcome.
