### ISSUE TITLE
Firefox 55 Nightly: Can’t request permissions from the toolbar button

### ISSUE THREAD

**Issue by ExE-Boss** [sindresorhus/notifier-for-github#130]
As it turns out, Mozilla had the “bright” idea to disallow asking for optional permissions when the user clicks on the toolbar button, despite the official MDN documentation on the [`permissions`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/permissions/request) API saying that it should work.

### Possible solutions:
1. Wait for Mozilla to fix their browser (again)
    Should hopefully happen by the time Firefox 55 Stable comes out, which will be two months from now.
2. Implement #71

**Comment by notlmn** [comment]
Permissions did work but now the whole extension is basically broke (every other extension using Foxified) because Firefox blocks unsigned extensions and requires some tedious steps to make it work.

Please add any additional comments in #137, also to discuss direct AMO support.
