### ISSUE TITLE
Does only show them when clicked once

### ISSUE THREAD

**Issue by thebigsmileXD** [sindresorhus/notifier-for-github#134]
I recently got an issue that the addon does not show the badges anymore until i click on it.. After that it fetches the count just fine, until i restart the browser. I am using Opera, and installed it via https://addons.opera.com/de/extensions/details/download-chrome-extension-9/?display=en

**Comment by pasindujw** [comment]
Same happened with Chrome.

**Comment by notlmn** [comment]
Duplicate of #132.
