### ISSUE TITLE
optionally link to https://notifications.githubapp.com

### ISSUE THREAD

**Issue by boblannon** [sindresorhus/notifier-for-github#139]
I personally prefer to read notifications using the alternative https://notifications.githubapp.com app. It'd be nice to be able to optionally change the click behavior of the extension icon and be taken to that url rather than https://github.com/notifications/

**Comment by notlmn** [comment]
This requires another input field and added maintenance. The idea is to keep the extension as minimal as possible.

The extension is provided with sensible defaults that works for most users, but feel free to reopen if you have a strong use-case.
