### ISSUE TITLE
Snooze notifications

### ISSUE THREAD

**Issue by dhruvdutt** [sindresorhus/notifier-for-github#146]
Add an option to snooze notifications for some period.

"Snooze [x] period". I think 20/30 mins is a good period.

One of the apps that does this it is Pushbullet.

![image](https://user-images.githubusercontent.com/5961873/38571764-0e307e26-3d0f-11e8-96c8-8fab6cfd9f39.png)

**Comment by sindresorhus** [comment]
For macOS, you can just turn on "Do Not Disturb".

There seems to be something similar for Windows too: https://www.howtogeek.com/233215/how-to-configure-do-not-disturb-mode-in-windows-10/

**Comment by notlmn** [comment]
If you want to, you can disable notifications in the options page and not forget to turn it back on.

And if you want complete DnD, try using the option mentioned by @sindresorhus above.
