### ISSUE TITLE
Latest update broke the extension pretty bad.

### ISSUE THREAD

**Issue by brandonbothell** [sindresorhus/notifier-for-github#157]
It seems that you didn't update your browser-polyfill or whatever, because you used one too many arguments in the contains() function call. Clicking on the extension icon doesn't open the Github notification page, and I can't turn on desktop notifications on Chrome.

**Comment by ankurk91** [comment]
Should be fixed in https://github.com/sindresorhus/notifier-for-github/commit/a04e89156f788ceea8012bbc5d65fb0260bb4b93

**Comment by notlmn** [comment]
The issue is fixed in the latest Chrome webstore release `18.7.25.1814` or newer.

Update the extension to get the latest release.

**Comment by sindresorhus** [comment]
Duplicate of #155
