### ISSUE TITLE
Missing access token

### ISSUE THREAD

**Issue by Alpvax** [sindresorhus/notifier-for-github#158]
Recently updated, and now the icon shows a red cross. hovering over it displays a tooltip saying "Missing access token, please create one and enter it in Options".
My access token still exists, and it has worked perfectly until now.

To clarify, I was on Chrome 67.0.3396.99, but it still isn't working on 68.0.3440.75.
I did notice it after I updated my GitHub to use the new dashboard, but I doubt they changed the API for that.

**Comment by AgrimPrasad** [comment]
See this issue too on Google Chrome Version 67.0.3396.99 after recent update. The chrome extension seems quite broken now, as no unread count is visible and no notifications are being seen anymore.

**Comment by notlmn** [comment]
Notifications are fixed in the release `18.7.27.1445`.

But as of the token can you try entering the token again?

**Comment by ramereth** [comment]
Entering the token again seems to have worked.

**Comment by notlmn** [comment]
I highly suspect it has to do something with `webext-options-sync` saving the options only after an input event.

@alpvax can you try re-entering the token and confirm if that works for you?

**Comment by Alpvax** [comment]
I can confirm that re-entering the key fixed the issue. I would suggest changing the placeholder text, as I had overlooked that the key was in fact empty, assuming that was my key. Maybe just prepend "Example key:".

Closing as the actual issue is resolved.
