### ISSUE TITLE
Click a desktop notification alway open https://github.com/notifications

### ISSUE THREAD

**Issue by gylns** [sindresorhus/notifier-for-github#159]
is it possible to open the notification's url?

**Comment by MartinKolarik** [comment]
For me clicking on desktop notification doesn't open anything at all now after Chrome switched to native Windows 10 notifications.

**Comment by notlmn** [comment]
@MartinKolarik Thanks for reporting, but according to [this](https://bugs.chromium.org/p/chromium/issues/detail?id=873428#c19) issue, it is a bug in Chrome and expected to be fixed in the next (v69) release.

**Comment by MartinKolarik** [comment]
@notlmn thanks, I'll wait for v69 then.

**Comment by WBGF** [comment]
Terimakasih atas Pemberitahuan
