### ISSUE TITLE
Übersetzungsfehler

### ISSUE THREAD

**Issue by h3ndrk** [sindresorhus/notifier-for-github#16]
Englische Übersetzung fehlerhaft:
- Benachrichtigung: "Es fällt nichts aus."
- Filterbeschriftungen in der Filteractivity

**Comment by sindresorhus** [comment]
English please.

**Comment by NIPE-SYSTEMS** [comment]
I'm really sorry, wrong repo. (Also with the other issue.)

By the way i'm using the extension and it's very cool. Nice work!
