### ISSUE TITLE
Errors on using on enterprise github 

### ISSUE THREAD

**Issue by DigitalPig** [sindresorhus/notifier-for-github#163]
I installed this extension from Chrome store and setup it with correct end point of enterprise github API URL but am having issues with the notification. Checked console and the error is:

```
Failed to load https://github.xxx.farpgitanune.com/api/v3/notifications?participating=true&per_page=1: Response for preflight is invalid (redirect)
```

I have created personal access token and put the token in the setting page as well. But it does not help. Any idea why?

**Comment by notlmn** [comment]
This might be a CORS issue, where the [preflight request is being redirected](https://stackoverflow.com/a/42172732). One possible solution according to [this](https://stackoverflow.com/a/35452170) StackOverflow answer is to specify a `Content-Type` header in the requests.

But I do not have access to a GitHub Enterprise domain to test this on, can you test this for me?

**Comment by Jonathan75** [comment]
I could test it for you.

**Comment by notlmn** [comment]
If you already know how to test extensions skip the following section

1. Clone the repo
1. Add a `Content-Type` header [here](https://github.com/sindresorhus/notifier-for-github/blob/64eaa9f96fa6d30ed526627e4d2f902df1f6f218/source/lib/api.js#L39-L44) (maybe `application/json`)
1. Install packages and run `npm run watch` in the project directory
1. In Chrome, navigate to `chrome://extensions` and enable developer mode
1. Load unpacked extension and select the `distribution` directory created by webpack
1. Test usually as if you have an extension installed from store

Don't forget to disable the store version while developing.

Thanks for willing to test!

**Comment by Jonathan75** [comment]
@notlmn Gave it a shot and still unknown error.  Thanks for the clear instructions.  Here is what I tried in case I did not interpret the change correctly.  https://github.com/sindresorhus/notifier-for-github/compare/master...Jonathan75:enterprise-github

**Comment by Jonathan75** [comment]
Oh my, I did get it to work. 🤦‍♂️  The links in the options take you to github.com which will not help me with the enterprise site. 
![image](https://user-images.githubusercontent.com/559973/45425170-9bb43c80-b666-11e8-8501-748d9426c237.png)
The extenchen from the store version also worked with the correct token.

**Comment by notlmn** [comment]
Thanks @jonathan75 for testing that for me.

> The links in the options take you to github.com which will not help me with the enterprise site

Yeah the link is generic 😅

------------------

@digitalpig do you still have this issue?
