### ISSUE TITLE
Add https://github.com/notifications?all=1 to open tab checker

### ISSUE THREAD

**Issue by RomanKornev** [sindresorhus/notifier-for-github#167]
Currently, the extension doesn't detect https://github.com/notifications?all=1 as open notifications page and always opens a new page on icon click instead of switching to already existing one.

**Comment by notlmn** [comment]
Ohh, that seems to be a thing that we could add, I'll try to sneak that condition in for handling tabs.

(As of the time, I'm a bit busy sorting things out after taking some time off GitHub, I'm still following all the issues though as they are created)
