### ISSUE TITLE
Shorter Intervals

### ISSUE THREAD

**Issue by vinkla** [sindresorhus/notifier-for-github#17]
The chrome extension works great and I use it every day. Though, there is one thing I would like to update. The notification fetching interval. Sometime it can take quite a long to update the little notification badge on the icon. Maybe we could add it to the settings page? Then everyone could specify their own preferences. What do you think?

**Comment by sindresorhus** [comment]
Duplicate of #11

**Comment by vinkla** [comment]
Okay. Thanks.
