### ISSUE TITLE
Add an option to use "All notifications" tab instead of "Unread"

### ISSUE THREAD

**Issue by RomanKornev** [sindresorhus/notifier-for-github#171]
Exactly like we have for `useParticipating` which opens https://github.com/notifications/participating.
Talked about in https://github.com/sindresorhus/notifier-for-github/pull/170:
It's somewhat confusing that clicking on the extension button while having https://github.com/notifications?all=1 open brings up https://github.com/notifications in the same tab instead.

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but we're going to pass on this.
