### ISSUE TITLE
Clicking a desktop notification opens an API URL

### ISSUE THREAD

**Issue by vith** [sindresorhus/notifier-for-github#177]
For example, the new tab's location will be something like:

`https://api.github.com/repos/sindresorhus/notifier-for-github/issues/177`

which displays as content:

```json
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/issues/#get-a-single-issue"
}
```

when the location opened should be:

`https://github.com/sindresorhus/notifier-for-github/issues/177`

**Comment by notlmn** [comment]
What was the type of notification you received? Issue? PR? Or something else?

And if you could provide actual link from the notification list from GitHub UI (to see if there are any additional fragment or search parameters that might be causing this issue).

**Comment by szhangpitt** [comment]
I'm noticing this too. I am using enterprise github which has a different domain, but upon clicking a desktop notification on a PR, it goes to the api endpiont.

**Comment by vith** [comment]
Hmm. *This* issue's notification did actually work.

Looking at my notifications list, the one that prompted me to report this problem was a new issue being opened in a private repo, with no fragment or parameters in the link. Just `https://github.com/<org>/<repo>/issues/<id>`.

**Comment by notlmn** [comment]
This is because of #174.

GitHub's API doesn't provide a way to get link that directly navigates the user to the "last unread comment", like it does when you click on notification on GitHub's notification page.

So we try to construct one for ourselves by looking at some of the fields that the API provides (#174), which is far from perfect.

From what information is provided, I'm guessing that this fails to build URL for new issues and PR notifications, will look into it in a bit (or someone can debug this for me 😉).

**Comment by vith** [comment]
It happened again, this time it was a comment on a private repo issue. So public working, private breaking seems to be the pattern for me.

I debugged the extension a bit. When one of these private repo notifications is clicked,  this request https://github.com/sindresorhus/notifier-for-github/blob/0b60d64df8eb06057e69cd4413d3f7ab645601be/source/lib/notifications-service.js#L32 returns a 404.

The try/catch block wrapping that request swallows the error though, so this return statement https://github.com/sindresorhus/notifier-for-github/blob/0b60d64df8eb06057e69cd4413d3f7ab645601be/source/lib/notifications-service.js#L75 is reached.

I modified my personal access token, adding the `repo` scope, and now private notifications are working when clicked.

**Comment by vith** [comment]
I believe I saw a `"private": true` field on the notification object as well.

It looks like it's possible to check what scopes are granted by the token: https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#requested-scopes-and-granted-scopes

So maybe the extension could check those things and show a warning that the scopes are insufficient.

**Comment by notlmn** [comment]
Thanks for looking into this @vith.

-------------------

> So maybe the extension could check those things and show a warning that the scopes are insufficient.

We already show that the extensions needs `repo` OAuth permission to be able to receive notifications from private repositories. So having to add handler to check for sufficient permissions is way beyond what the extension is supposed to do.

![image](https://user-images.githubusercontent.com/37769974/57506146-8b994d80-7318-11e9-86f5-d89317fb0687.png)

--------------------

Generally the API returns a `401 (Unauthorized)` if the token does not have enough scopes granted, not `404`. And I have no idea why that is happening.

But the `catch` block swallowing the error _is_ a real issue. Previously we opened the notifications tab if the `fetch` failed. But in this case we can still recover the URL to navigate to from `notificationUrl`.

I'd be very glad if someone sent a PR to fix this 🙏 (or wait till I can, travelling a lot lately 😅).

**Comment by notlmn** [comment]
The latest release (`19.5.13.1520`) should fix this issue.

If you find any bugs, feel free to open an issue.
