### ISSUE TITLE
Option to have notification stay until the user acknowledges it

### ISSUE THREAD

**Issue by JMTyler** [sindresorhus/notifier-for-github#178]
Feature Request:

It would be nice to have a toggle in the options allowing the user to keep notifications from disappearing (perhaps unseen) until they've either clicked on it or closed it.  This can be easily implemented by adding the `requireInteraction: true` flag to the notification object generated by the [`getNotificationObject()`](https://github.com/sindresorhus/notifier-for-github/blob/master/source/lib/notifications-service.js#L90) function.

**Comment by notlmn** [comment]
Why do you want to have notifications on screen, most operating systems provide something like a notification center where you can always find your notifications.

Wouldn't this feature be distracting, and some operating systems (I might be wrong here) allow to show only one active notification on screen anyway.

**Comment by JMTyler** [comment]
I would likely clear the notification as soon as I saw it, but it would be nice to have it sitting there waiting for me if I stepped away from my computer for a few minutes (without needing to check the notification centre every time I sit down - the whole point of a notification is for you to see it _without_ needing to ask for it, IMHO).  Of course, the most important detail is that this is configurable (and off by default), because I understand the majority probably don't want this.

This feature would also make it more feasible to add a "Mark as Read" button to the notification (which I'm only associating with this feature because it wouldn't be as valuable if the notification disappeared before you could click it), and then we wouldn't have to open GitHub just to clear out notifications we didn't care about.

For what it's worth, if your only concern is that you don't see the value of spending _your own_ time on it but you otherwise aren't against the feature _existing_, I'd be happy to implement this at some point myself.  If, however, you'd avoid supporting the feature at all if you don't see the value in it, then I'm happy to continue discussing it.

**Comment by notlmn** [comment]
To be clear I'm not against any feature requests to the extension unless it provides some form of value.

I sounded against this as operating systems have a notification center that holds all of your notifications so you can get back to them later. Last time I checked, you cannot have more than one notification on the screen at once.

That's a neat little thing you pointed out there to add buttons to the notification itself. I'd like to try that myself at some point. 👌

There's nothing stopping you from taking a stab at this, even opening a PR so that we can discuss on how best to implement something like this. Feel free to tackle this at your own will. 🙂

**Comment by 5HT2** [comment]
This would be immensely helpful because on KDE this extensions notifications go away after ~1.5 seconds and I can't click on it fast enough usually.

**Comment by notlmn** [comment]
If you are talking about the amount of time a notification stays on screen, then I think on KDE you can do that using something like [this](https://unix.stackexchange.com/a/493564), I'm sure there's other ways to do the same on other Linux systems.

We could add actions to notifications themselves like "Mark as read", but Firefox [doesn't support](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/onButtonClicked#Browser_compatibility) listening to button clicks yet.

If anyone has additional use cases for this feature, I'd love to hear them. Until then I don't see how useful this feature could be (considering the limitations I've mentioned above).

**Comment by 5HT2** [comment]
Problem with that is that firefoxes notifications don't show on a timer, or with the important option that never automatically closes. For some reason they seem to just be unable to decide and close instantly. Oh well, i'll rely on the icon in the toolbar
