### ISSUE TITLE
Annoying notification sound every minute

### ISSUE THREAD

**Issue by martinvonwittich** [sindresorhus/notifier-for-github#179]
Since today, I'm suffering from an extremely annoying notification sound that seems to occur exactly every 60 seconds. What makes this so annoying is the fact that there is absolutely no visual indication where this notification sound is coming from - no notification popup, nothing's blinking, no Windows message, nothing. I went through the Windows sound settings and played each sound Windows had, but it wasn't of those. I then used Windows' volume mixer and raised the volume of all running applications bit by bit to isolate which application it was coming from, and it was Chrome.

I then closed most of my tabs, but the sound didn't go away. Finally, I went through my extensions and noticed that GitHub Notifier has an "Enable notification sound" option in its settings, which indicated that it could be a possible source. I then downloaded and played [bell.ogg](https://github.com/sindresorhus/notifier-for-github/blob/master/source/sounds/bell.ogg) from this repo, and lo and behold, that's the sound that has been driving me crazy for the last hour :(

Since I've disabled the "Enable notification sound", the annoying sound is finally gone.

Possibly useful information:

- Chrome 74.0.3729.169 
- Notifier for GitHub 19.5.28.1037
- I have to unread GitHub notifications (the extension is dispaying a "2" badge
- I wasn't logged in on GitHub when the issue started to occur (not sure if this is relevant as the extension uses a token?)

**Comment by notlmn** [comment]
Hmm, that's interesting. Looks like a caching issue to me, I might be wrong though.

Can you try disabling and re-enabling the extension, and maybe also try uninstalling and reinstalling the extension. Feel free to ping back if the issue still persists then.

**Comment by martinvonwittich** [comment]
The issue seems to have gone away on its own. I re-enabled notification sounds and marked an already read notification as unread, but it's not reoccurring. I'll report back if it should happen again.

Any tips in the meantime how I could debug this if I see it again?

**Comment by notlmn** [comment]
I assume you already know how to open the debugger for browser extensions, if not, then you can always lookup online for instructions for both Chrome and Firefox. Then you could put a breakpoint on the line that has the call to `playNotificationSound()`, and see if the debugger is paused on the line for each minute even if there are no new notifications.

As mentioned already, this is probably a malformed cache issue, as I don't see anyone reporting it. You likely will not experience it again, but to be sure I'm gonna keep this thread open until you can be sure that it this behavior is gone.

**Comment by martinvonwittich** [comment]
Your comment re-triggered the issue. I'll look around with the debugger :)

**Comment by martinvonwittich** [comment]
Unfortunately the issue went away after I commented on this ticket the last time, and it hasn't reoccurred so far. I'll just close this for the time being.

**Comment by martinvonwittich** [comment]
It's happening again, and I think this time I've figured it out. The following exception is logged whenever I hear the sound:

```
Uncaught (in promise) TypeError: Cannot read property 'create' of undefined
    at showNotifications (background.js:1183)
    at checkNotifications (background.js:1202)
    at async handleLastModified (background.js:1221)
```

For some reason, `browser.notifications` is `undefined` here:

```
  async function showNotifications(notifications) {
    for (const notification of notifications) {
      const notificationId = `github-notifier-${notification.id}`;
      const notificationObject = getNotificationObject(notification);
      await browser.notifications.create(notificationId, notificationObject);
      await local_store.set(notificationId, notification);
      await delay_default()(50);
    }
  }
```

If I'm reading the code correctly, the repeated ping sound then occurs because the exception prevents `handleLastModified` from updating the `lastModified` value in my local storage, so `lastModified` is always 1970-01-01. And then every `update` call runs into the same issue, causing a ping sound every 60 seconds.

I don't really know though why `browser.notifications` is undefined :/

**Comment by notlmn** [comment]
@martinvonwittich this might make a little bit of sense now, after your debugging.

From what I know, I suspect that this might be an issue with background pages being run in different order.

![image](https://user-images.githubusercontent.com/37769974/66267370-b77c1900-e84d-11e9-9b72-e75e75d0122a.png)

As mentioned in the manifest file, if the `background.js` file is run before the `browser-polyfill.min.js` file is loaded and run, then we might not have access to `browser.notifications`.

**Comment by notlmn** [comment]
Or it could be another issue where the user hasn't granted the notifications permission, but for some reason the "show notifications" options is set, using which the extension tries to access notifications API which is not granted.

If that's the case, can you try removing the extension entirely and installing it again, to see if this issue is related to caching in some way, also enabling and disabling notification options.

**Comment by martinvonwittich** [comment]
> As mentioned in the manifest file, if the background.js file is run before the browser-polyfill.min.js file is loaded and run, then we might not have access to browser.notifications.

I'm not really familiar with extension development, but as far as I can tell from several documentation sites, the way you do it seems to be correct:

https://github.com/mozilla/webextension-polyfill#basic-setup
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background

Also, when I type `browser` into the console of the extension inspector, it is defined and Chrome will autocomplete methods like `inspector` or `alarms`, and only `browser.notifications` is undefined:

```
> browser
< Proxy {}

> browser.notifications
< undefined
```

If I'm understanding this polyfill correctly, browser shouldn't be defined at all if the polyfill hasn't been loaded, should it? When I type it into the inspector of a normal page, it is undefined and Chrome won't complete any methods of it.

This leads me to believe that the polyfill has indeed been loaded correctly.

> Or it could be another issue where the user hasn't granted the notifications permission, but for some reason the "show notifications" options is set, using which the extension tries to access notifications API which is not granted.

I believe this is the case. I found the following code snippet to query the permissions: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/getAll#Examples

Running this in the inspector gives me:

```
< browser.permissions.getAll().then((result) => { console.log(result.permissions); console.log(result.origins) });
> Promise {<pending>}
> (2) ["alarms", "storage"]
> []
```

I'm wondering if this might have anything to do with the fact that I'm using Chrome sync. I probably installed the extension on my work computer, enabled the notifications and granted the notification permission. Chrome sync then synced the extension and its settings onto my home computer, but not the permissions?

I opened the extension settings and disabled and immediately re-enabled "Show desktop notifications", and it did ask me for permissions _once_. Further attempts to disable and re-enable the option won't ask for permissions again, so once the notifications permission has been granted, it stays. This again confirms that the permission was missing before.

Now the code snippet reports:

```
> (3) ["alarms", "notifications", "storage"]
```

**Comment by notlmn** [comment]
@martinvonwittich that's some epic debugging.

I really have no idea on why Chrome syncs options but not permissions, maybe it's a security feature.

In any case we should guard against the usage of notifications API, checking for permission again instead of directly relying on the options being synced.

I'm assuming this issue of yours is fixed once the permission has been granted. I'm gonna make a quick PR once I'm back at my keyboard.

Thanks for the debugging.

**Comment by martinvonwittich** [comment]
> I'm assuming this issue of yours is fixed once the permission has been granted. I'm gonna make a quick PR once I'm back at my keyboard.

I'm assuming so too. If not, I'll be back :)

**Comment by notlmn** [comment]
@martinvonwittich Feel free to opens this issue again if you face any issues. Closing this for now.
