### ISSUE TITLE
[Chrome] Unknown error. Unchecked runtime.lastError: The message port closed before a response was received.

### ISSUE THREAD

**Issue by phanduytunglinh** [sindresorhus/notifier-for-github#183]
Hello, I',m using Chrome Version 75.0.3770.100 and I don't receive any notifications for new updates. It says "Unknown error" instead of notification count and when I check browser's console, there is something like this. 
![image](https://user-images.githubusercontent.com/7687993/59817213-0b73f800-935a-11e9-8659-c5edf48e225a.png)

More information:
- Github Enterprise
- Repository is controled by organization
- Access Token is generated in my side.
- Here is my setting.
![image](https://user-images.githubusercontent.com/7687993/59817648-b933d680-935b-11e9-9320-9cc717e5bd79.png)

**Comment by notlmn** [comment]
That looks like a server error, and I have no way to debug this with GitHub Enterprise. So can you debug this for me?

**Comment by notlmn** [comment]
As this looks like a server related issue, I'm going to close this for now.

Feel free to reopen the issue if you still experience the issue and think that this is an issue on the extension side.
