### ISSUE TITLE
Notifier for GH Enterprise always adds /api/v3 when clicking on notifications

### ISSUE THREAD

**Issue by charliegroll** [sindresorhus/notifier-for-github#188]
Instead of `https://github.company.it/my/repo/pull/1` I get sent to `https://github.company.it/api/v3/my/repo/pull/1` when clicking OS X notifications

**Comment by notlmn** [comment]
Any kind of API error should generally be handled by [`issueOrPRHandler`](https://github.com/sindresorhus/notifier-for-github/blob/329461be86c2b9c64ad275b181578ce3dbb28a9b/source/lib/notifications-service.js#L22).

Even if that fails, the extension should open the notifications page. Are you on GitHub Enterprise and what version are you using.

**Comment by charliegroll** [comment]
GitHub Enterprise 2.15.17 and Notifier version 19.6.25.752

**Comment by notlmn** [comment]
@charliegroll This was a bug for extracting URLs from APIs, where the pathname is different for regular GitHub (`https://api.github.com/repos/user/reponame/pulls/1`) and Enterprise GitHub (`https://company.com/api/v3/repos/user/reponame/pulls/1`).

Thanks for pointing this issue out. Expect a new release by the end of the day.
