### ISSUE TITLE
feature: Allow to unread notification after opening the issue/pr from issue/pr

### ISSUE THREAD

**Issue by WaleedAshraf** [sindresorhus/notifier-for-github#191]
Hi,

This extension is really useful. One thing I miss in Github UI is to mark a notification as unread if you accidentally clicked it OR if you don't have time to go through it at the moment and you want to keep the notification.

It can be done from the [notification page](https://github.com/notifications) by clicking the dot icon, but if you closed that page, you lose it. Then you have to open all seen notifications and find the one you want to mark as unread. This whole process seems too much for me.

I want to have something like this:
![Untitled](https://user-images.githubusercontent.com/8335457/63891959-b520d680-c9e6-11e9-95bd-eb2826cbcc64.png)

I think this can be done easily by making a call to notification api
`POST https://github.com/notifications/unmark?id={notificationId}`

As the user will be one an issue / pr. So we will have issue/pr ID.
We can get all the notifications of the user. And every notification object has a link to its PR/Issue.

```
 "subject": {
      "title": "Greetings",
      "url": "https://api.github.com/repos/octokit/octokit.rb/issues/123",
      "latest_comment_url": "https://api.github.com/repos/octokit/octokit.rb/issues/comments/123",
      "type": "Issue"
    },
``` 
Here: https://developer.github.com/v3/activity/notifications/#response

From there, we can match the PR/Issue and get the ID of notification and then mark it as unread.

I already have a chrome ext for github: https://github.com/WaleedAshraf/github-title-bar
But recently GitHub released this feature them self and my ext became useless :D . So, I was planning to re-write it for this feature. But I thought it'd be good if we can do it here?

Let me know what you think, or if there is a better option.

**Comment by notlmn** [comment]
What you are essentially describing is the ["Mark as unread"](https://github.com/sindresorhus/refined-github/blob/master/source/features/mark-unread.tsx) feature of [Refined GitHub](https://github.com/sindresorhus/refined-github) extension.

The feature has its downsides of course, all the "marking as unread" part is done on the client side. There isn't an API available to mark a notification as unread, even the HTTP endpoint used by GitHub uses some "thread ids" to mark or unmark notifications, not the `"id"` field that you see in the API response. This behavior is explained in more detail [here](https://github.com/sindresorhus/refined-github/issues/2271#issuecomment-515437744).

Even if this feature could be implemented, this feature is way out of the scope of this extension. We do not interact with GitHub's UI in any way, that would be the job of Refined GitHub extension mentioned above.

I sure hope that GitHub can improve its notifications interface where we keep losing notifications and have to dig up all notifications page, which I end up doing most of the times too.

Thanks for opening the issue btw.

**Comment by WaleedAshraf** [comment]
@notlmn thanks, I didn't know about Refined GitHub. It has what I need.
You are right, Github should improve notif UI and features. Against, thank for your effort in this ext. 👍
