### ISSUE TITLE
Add ability to change refresh rate

### ISSUE THREAD

**Issue by Michael-Ziluck** [sindresorhus/notifier-for-github#195]
Some people might want the notifications to update more or less frequently. Currently this is not possible.

**Comment by notlmn** [comment]
The current implementation uses the [`alarms`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/alarms) API, which according to [Chrome docs](https://developer.chrome.com/extensions/alarms#method-create) limits scheduling alarms to at most 1 alarm per minute. So there's no option for going more frequently (FYI, the extension automatically updates count, regardless of the alarm, for every potential notification open: #182).

And I don't see why you want it to update less frequently, any use-cases you could mention for me?

**Comment by Michael-Ziluck** [comment]
As for how often it updates, why not have a separate value for how often it sends the alarm and for how often it updates? I personally have the noise and push notifications turned off, but would love it if the icons updated every 5 seconds or so rather than every 60.

As for more frequently, I'm not really sure someone's motivation but if it isn't much work I don't see the harm.

**Comment by notlmn** [comment]
> As for how often it updates, why not have a separate value for how often it sends the alarm and for how often it updates? I personally have the noise and push notifications turned off, but would love it if the icons updated every 5 seconds or so rather than every 60.

We cannot have an alarm that can be triggered multiple times over a single minute. Refer to my comment above on why.

---------------

> As for more frequently, I'm not really sure someone's motivation but if it isn't much work I don't see the harm.

I was referring why people would make it update less frequent, not on why they would like it to upgrade more frequent.

**Comment by Michael-Ziluck** [comment]
@notlmn I want it to query GitHub for notifications more often than 60 seconds but NOT send an alarm. This would be useful to see the icon update regularly even if the notification does not go off.

For the second part, I meant to say less frequently.

**Comment by dirathea** [comment]
CMIIW, But I think @ZiluckMichael might missed this one, [alarms](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/alarms) means the interval of an extension to do something, not necessary for sending notifications, or alerting, but maybe doing action in interval manner. Think this `alarm` like `setInterval` or `setTimeout` but for browser extension.

there are 2 limitations of your request to do Github request more often than 60 seconds.

1. Clear limitation of browser extension to handle alarm stated [here](https://developer.chrome.com/extensions/alarms#method-create)
2. Github API also asks developer to [respect their Poll Interval](https://developer.github.com/v3/activity/notifications/)

Hope this information helps!

**Comment by Michael-Ziluck** [comment]
@dirathea That actually clears things up a lot. I understand that limitation now. Sorry for the confusion! Thanks!
