### ISSUE TITLE
https should not be hard-coded in the notification page URL

### ISSUE THREAD

**Issue by ava1ar** [sindresorhus/notifier-for-github#198]
I am using Firefox extension with enterprise github and it is not https-enabled (I know this is bad, but this is what it is). Pretty much everything works, except the opening notifications page when clicking on add-in icon - there is `https` hardcoded in the URL construction: https://github.com/sindresorhus/notifier-for-github/blob/master/source/lib/api.js#L17. Can we somehow use protocol from the `${rootUrl}` provided in add-in settings? Thanks!

**Comment by notlmn** [comment]
Though I don't recommend this, I understand your pain. Feel free to make a PR with the changes.

(Also spam your admin to enable HTTPS on your GHE domain)

**Comment by ava1ar** [comment]
@notlmn Thanks, I will prepare a small PR which addresses the issue in few weeks after I am back from vacation. Thanks for your work!
