### ISSUE TITLE
Complains about no internet connection

### ISSUE THREAD

**Issue by awbushnell** [sindresorhus/notifier-for-github#199]
I just installed this extension in hopes of avoiding email notifications, but when I launch Chrome, the extension has  ? mark over it and a tooltip that reads:   "You have to be connected to the internet"

If I click the button it brings me to my notification page, but I am guessing that tooltip indicates it is not able to properly work/notify me?

**Comment by notlmn** [comment]
Chrome sometimes disables the alarms API we use to periodically check for new notifications, to save power or limit time for which an extension runs.

This behavior is not predictable, and the events that Chrome pushes to the extension are unreliable. This usually happens after device wake up from sleep.

Which version of Chrome and this extension are you on?

**Comment by awbushnell** [comment]
@notlmn  I have gotten things to work.. FWIW, here is what I did as I am not sure which of these addressed the issue:

- I uninstalled the extension
- I reinstalled and generated a new token for access to our repositories
- Used that new token to set things up.

Upon that, things now seem to be working and I do not see the issue currently.  The version of Chrome I am on is:  Version 79.0.3945.130 (Official Build) (64-bit)
