### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by attilaolah** [sindresorhus/notifier-for-github#20]
@gcochard, would you mind cherry-picking your commits for this? I can't pull directly from https://github.com/sindresorhus/github-notifier-chrome/compare/master...gcochard:master, because of the squashed merge of #18.

I'd like to work on #12 soon, and it would be much easier if the CI had my back.

**Comment by gcochard** [comment]
Will do this today or tonight :smile:

**Comment by sindresorhus** [comment]
How would you test code using Chrome Extensions APIs with a CI?

**Comment by gcochard** [comment]
I have most of the chrome extension APIs mocked out. I will then simply call the handler function and ensure the correct method calls occurred. I plan to mock out the gh api responses as well, so that we can ensure the badge API is called with the proper values for 0, 1, many, etc.

**Comment by sindresorhus** [comment]
Ah, sounds good :)

**Comment by gcochard** [comment]
Closed via #24
