### ISSUE TITLE
Use of token depreciated by GitHub

### ISSUE THREAD

**Issue by jmaneyrol69** [sindresorhus/notifier-for-github#200]
Hi,

I have recently received the following message from the Github team:

>On February 7th, 2020 at 10:01 (UTC) your personal access token (Notifier for GitHub extension) using Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0 was used as part of a query parameter to access an endpoint through the GitHub API:

>https://api.github.com/notifications

>Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.

>Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

>Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

>Thanks,
The GitHub Team

However, I have not been able to find anyway to use Authorization HTTP header instead of access token in Notifier for Github (I am using the extension for Firefox, Opera and Chrome).

Regards

**Comment by notlmn** [comment]
That deprecation is about OAuth applications using the standard auth flow to get an access token, that happens through URL and those tokens are relatively temporary.

We do not use OAuth flow to get a token, we request the user to generate a token in settings and paste that in our options, this token is for long term use.

Are you sure that the email you are receiving if because of this extension?

**Comment by jmaneyrol69** [comment]
Hi @notlmn ,

Yes, I don't use any other Github App with OAuth, and in the email, the
Github notifier app is clearly identified:

>On February 6th, 2020 at 16:36 (UTC) your personal access token (*Notifier
> for GitHub extension*) using Mozilla/5.0 (Windows NT 10.0; Win64; x64;
> rv:72.0) Gecko/20100101 Firefox/72.0 was used as part of a query parameter
> to access an endpoint through the GitHub API
>

Also, I have some colleagues at work who use the Github Notifier app and they received this
message too.

Best regards,

**Comment by notlmn** [comment]
Can you confirm that you are not using that token you generated for this extension and using it somewhere else, like in another extension.

Because we don't send the token in query-params, and the only place we use the token in code is in `source/lib/api.js` ([verify](https://github.com/sindresorhus/notifier-for-github/search?q=token&type=Code)).

**Comment by jmaneyrol69** [comment]
Indeed, I was using the same token with Octotree. I will use a different
one and let you know if I still get notifications for Gtihub notifier from
Github.

Thanks for the precision.
Regards,

**Comment by jmaneyrol69** [comment]
Hi,

I've just been notified by Github again:

Hi @jmaneyrol69,
>
> On February 13th, 2020 at 10:11 (UTC) your personal access token (Notifier
> for GitHub extension) using Mozilla/5.0 (Windows NT 10.0; Win64; x64;
> rv:72.0) Gecko/20100101 Firefox/72.0 was used as part of a query parameter
> to access an endpoint through the GitHub API:
>
> https://api.github.com/notifications
>
> Please use the Authorization HTTP header instead, as using the
> `access_token` query parameter is deprecated and will be removed July 1st,
> 2020.
>
> Depending on your API usage, we'll be sending you this email reminder once
> every 3 days for each token and User-Agent used in API calls made on your
> behalf.
> Just one URL that was accessed with a token and User-Agent combination
> will be listed in the email reminder, not all.
>
> Visit
> https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters
> for more information.
>
> Thanks,
> The GitHub Team


This time, I'm pretty sure this is not another app as I'm using a different
token for Octotree.

Regards,

**Comment by notlmn** [comment]
Sorry but none of have been able to see this behavior, or have seen anyone report it. We do not even send tokens in query parameters, we use headers for that.

I suggest you to revoke all your existing tokens and generate new one for each extension you currently use, and see if that helps you.

Hope this helps!

**Comment by jmaneyrol69** [comment]
Hi Laxman,

I haven't received any new notifications from github so far and github
notifier works as expected.
I guess this was a false alarm.

Thank you very much for your support.
Best regards,
Julien Maneyrol
