### ISSUE TITLE
Layout issue with Options modal on Edge (Chromium)

### ISSUE THREAD

**Issue by coliff** [sindresorhus/notifier-for-github#204]
I noticed that the options modal window in Microsoft Edge (Chromium) v81 for Windows 10 displays narrower than Chrome and it causes minor layout issues.

![image](https://user-images.githubusercontent.com/1212885/76843109-a87aa780-687e-11ea-8b15-d85644c37b24.png)

Not a massive problem, and I realise that Edge isn't listed as an officially supported browser for this extension but thought I'd log this issue anyway.

**Comment by notlmn** [comment]
Thanks for raising the issue @coliff, have published a fix, expect a new release available in store in the next few days.
