### ISSUE TITLE
Notifications from discussions no longer show using GitHub beta notifications

### ISSUE THREAD

**Issue by myii** [sindresorhus/notifier-for-github#206]
Before I switched to the GitHub beta notifications, I used to get notifications for everything.  Since adopting the beta, I've noticed that I no longer get a notification if there's a new comment in a discussion.  But if go to any GitHub page manually, I'll see the blue circle on the notifications bell.

**Comment by notlmn** [comment]
We're still having issues understanding how GitHub handles new notifications being marked as read and done. Ideally it should not be changed in the API, which would be a breaking change from their end.

Notifications beta UI should not affect the API, even if it does, that UI is still in beta.

We will be monitoring this issue closely for the next few days, please be patient.

**Comment by myii** [comment]
@notlmn Sure, thanks for this add-on, just wanted to make sure you were aware of the situation.

**Comment by notlmn** [comment]
I just got here from a desktop notification generated by this extension, can you mention what OS/Browser combination you are on?

(P.S: I do have Notifications Beta enabled)

**Comment by myii** [comment]
Ubuntu 19.10, Firefox 75.0b9 (64-bit) -- developer edition.

As I said, all of the notifications are still working _except_ for **GitHub discussions**.

**Comment by notlmn** [comment]
If you are referring to discussions as in PR discussions, I also got a notification for discussions happening in a PR (specifically review comments on code) from a repo I watch.

Maybe what you are seeing #132. But that goes away when you click on extension icon in toolbar. Can you confirm?

Also can you test this one stable edition and not on developer edition, we do not support alpha/beta/dev/canary browser versions?

**Comment by myii** [comment]
@notlmn I'm referring to these discussions:

* https://help.github.com/en/github/building-a-strong-community/about-team-discussions

The notifications for these were also working before I switched to the beta.

**Comment by notlmn** [comment]
I've tested this on and off beta, but GitHub doesn't seem to send any responses of team discussions (also team mentions in team discussions) in the API response (anymore?). I can't know if they sent them before, because none of us use(d) teams.

Maybe someone from GitHub (sorry @lukehefson) can point us in the right direction.

**Comment by myii** [comment]
@notlmn If it's any use, the blue circle still shows up in the GitHub UI, so it does appear as a notification within GitHub itself.  As you said, it may no longer be available in the API response.

**Comment by notlmn** [comment]
Yes they do appear on the web notifications UI, but their web UI does not use the public GitHub API they have, but is tightly coupled with some internal logic that we (the public) do have access to.

**Comment by WaleedAshraf** [comment]
One more thing, if we could do with beta notification, when going to notification page, also add filter " is:unread", that way it'll only show the unread notifications.
Should I open a new issue for this as nice to have? I'll also see if I can work on it.

**Comment by notlmn** [comment]
@WaleedAshraf, GitHub preserves your all/unread filters by default and adds them when you load that page. If that is not what you are referring to, feel free to open a new issue and we can discuss that there.

**Comment by WaleedAshraf** [comment]
@notlmn Yup, sorry. it's working fine. I may have been going to wrong tab. 👍

**Comment by notlmn** [comment]
This is not something happening at our end. We show notifications that are available to us by the GitHub API.

Please raise a request on https://support.github.com/contact
