### ISSUE TITLE
Make offline warning optional

### ISSUE THREAD

**Issue by brettz9** [sindresorhus/notifier-for-github#208]
Hi,

Just starting using and this looks like a great tool!

Was wondering if, particularly for those of us on easily disrupted connections, you could make the warning icon optional? It can be a little distracting to see the red there so frequently.

Thanks!

**Comment by notlmn** [comment]
I live on flaky WiFi too, but the thing is that if we do not show the warning, the user does not know that they are offline, think that they do not have any notifications, and come back here to raise an issue to show them if they are offline.

When you are offline, the badge should be yellow in color, not red. Browsers sometime think that they are online, despite being offline (and vice versa), which makes us to think that the API is failing, hence rending the red color.

I'm glad you liked the extension. Happy to hear on how we can keep improving it.
