### ISSUE TITLE
Support for multiple notification endpoints

### ISSUE THREAD

**Issue by eprouty** [sindresorhus/notifier-for-github#21]
Currently the notifier only allows you to enter one notification endpoint.  I'd like this to be able to support both the public and enterprise instances that I use, with potential for `n` notification endpoints.

I have some ideas for this and will either post some mockups of how this could work.  Suggestions welcome.

**Comment by sindresorhus** [comment]
Some mockups or behaviour description would be welcome as I don't see how this could work nicely.

@attilaolah @gcochard @jamime Thoughts?
