### ISSUE TITLE
Go to subscriptions if no unread notifications

### ISSUE THREAD

**Issue by maxoku** [sindresorhus/notifier-for-github#213]
Could the button lead to subscriptions instead of (empty) notification page if there are no unread notifications? It could be a setting to choose what page would be opened after clicking on toolbar button.

**Comment by sindresorhus** [comment]
> lead to subscriptions

What is "subscriptions"? Include a link.

Any explain why that would be useful.

**Comment by maxoku** [comment]
O course. Here's the [link](https://github.com/notifications/subscriptions).
On this page I can view topics I subscribe and have quick access to them. New notification page doesn't include quick access to subscription page, so it would be nice that the toolbar button could directly open it.
Managing subscriptions isn't only to response to new answers, but also returning to them to view again posted there informations or provide new ones any time.

**Comment by notlmn** [comment]
It is highly unlikely that a user goes to subscriptions to manage them, atleast not as frequent as accessing the notifications page.

And also we have a feature where clicking on the extension takes you to a notifications tab, if you already have one opened. In that case, opening subscriptions page would conflict that behaviour.

This also requires an API call when the user clicks on the icon, and also wait for that request to complete before opening a page. Or would require accessing the DOM, which we do not do, and can likely be a feature for [Refined GitHub](https://github.com/sindresorhus/refined-github).

Neither of which is we are considering to do, so I'll a pass on this.

**Comment by maxoku** [comment]
There just could be a setting to choose what page would be opened.

**Comment by notlmn** [comment]
> This also requires an API call when the user clicks on the icon, and also wait for that request to complete before opening a page. Or would require accessing the DOM, which we do not do, and can likely be a feature for Refined GitHub.

☝️

**Comment by maxoku** [comment]
I don't understand what is the problem and how an other add-on could help me.

**Comment by notlmn** [comment]
1. We do not interact with page content, and we'd like to keep it that way. This requires adding new permissions, new tests, and more. Refined GitHub is likely a better to suggest any changes like this, which is why I pointed you to that project.
1. Your request of redirecting to "subscriptions page" is too subjective. Some people might even want to go to saved / done view instead.

**Comment by maxoku** [comment]
1. I never said I want to interact with a page content.
2. So a setting in which the user could define where to go would be a good idea.

**Comment by notlmn** [comment]
> 1. I never said I want to interact with a page content.

I said that implementing such feature would required doing something like that.

-------

> 2. So a setting in which the user could define where to go would be a good idea.

There are so many possibilities of states for such option, especially with GitHub offering custom filters.

-------

The idea of the extension is to keep it simple, and do the one thing best it is supposed to do. Your feature requests are not valid in the context of this extension, which is why I pointed you to a different project to suggest this change.

**Comment by maxoku** [comment]
> There are so many possibilities of states for such option, especially with GitHub offering custom filters.

What exactly? What custom filters?

> Your feature requests are not valid in the context of this extension

There is only one request. And it is valid. It's about setting what will be opened after clicking on toolbar button of **this** extension.

> which is why I pointed you to a different project to suggest this change.

I don't understand how that other add-on could help me?

**Comment by notlmn** [comment]
> What exactly? What custom filters?

![image](https://user-images.githubusercontent.com/37769974/82777102-bc3c1e80-9e6a-11ea-8f5a-e66231e044a9.png)

These.

-----------

> There is only one request. And it is valid. It's about setting what will be opened after clicking on toolbar button of **this** extension.

There are multiple pages that the user could go to when there are no notifications. You are just suggesting one possible such page. Which is not intuitive to the user at all.

I don't think that this feature could even be accepted as an opt-in feature.
