### ISSUE TITLE
Clicking on `create a token` button kills option page

### ISSUE THREAD

**Issue by evandrocoan** [sindresorhus/notifier-for-github#215]
1. Open the options page
   ![image](https://user-images.githubusercontent.com/5332158/85088524-b78f2f80-b1b6-11ea-8b07-628688ba3b1a.png)

1. After cliking on the options button
   ![image](https://user-images.githubusercontent.com/5332158/85088536-bc53e380-b1b6-11ea-8070-5115c844e83e.png)

**Comment by notlmn** [comment]
Fixed it in https://github.com/sindresorhus/notifier-for-github/commit/b241f6ead1e0f52d1bb434eddd544993041c4a25, you should be able to use this in the next release.

Meanwhile you can use "open in new tab" options that browsers provide.

Thanks for opening the issue.
