### ISSUE TITLE
Add drop-down menu listing recent notifications

### ISSUE THREAD

**Issue by evandrocoan** [sindresorhus/notifier-for-github#216]
For example, this discourse plugin has it: https://meta.discourse.org/t/google-chrome-extension-for-discourse-notifications/34496

![image](https://user-images.githubusercontent.com/5332158/85143290-f6a59b00-b21f-11ea-8759-843b3f2068b4.png)

**Comment by notlmn** [comment]
That is a good idea, but we'll do a pass on this, keeping it simple.

There is a [similar extension](https://github.com/tanmayrajani/notifications-preview-github) to what you ask, but works inside GitHub UI.
