### ISSUE TITLE
Show some kind of error when no token is set

### ISSUE THREAD

**Issue by shakeelmohamed** [sindresorhus/notifier-for-github#22]
I was about to report a bug saying the extension was broken... but my token got wiped out somehow. I'd like to see something red (circle, X, etc.) on the icon if the token is not set

**Comment by sindresorhus** [comment]
:+1:

**Comment by shakeelmohamed** [comment]
Here's 1/10 of the work, a red icon 
![icon-128-red](https://cloud.githubusercontent.com/assets/1480063/7904902/2dcada04-07c2-11e5-9dcf-9fcdc5ddf2a1.png)

**Comment by sindresorhus** [comment]
@shakeelmohamed Thanks, but I think we can use the icon badge for this, with a message in the tooltip.

**Comment by shakeelmohamed** [comment]
That works too

**Comment by nwinkler** [comment]
Looks like a recent update of Chrome wiped the tokens - I had the same issue...

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by shakeelmohamed** [comment]
I just looked through the code and understand how most of it works.

I'm thinking we may want a different character show if the error is either:

- empty token
- root URL is empty or `https://` (the default value on save)

My vote is for a nice big `X`, how about that?

**Comment by sindresorhus** [comment]
> empty token

:+1: 

> root URL is empty or https:// (the default value on save)

This is already handled in master or in https://github.com/sindresorhus/github-notifier-chrome/pull/42, don't remember which, by using the default public GitHub API URL if empty.

> My vote is for a nice big X, how about that?

:+1:

**Comment by shakeelmohamed** [comment]
> This is already handled in master or in #42, don't remember which, by using the default public GitHub API URL if empty.

Looks like f76b07a6e1831808c5f69b99a39b3ef4e68023f7.

I'll start working on a PR soon

**Comment by shakeelmohamed** [comment]
#44 has been merged :smile:
