### ISSUE TITLE
Notifier not updating despite having internet connection

### ISSUE THREAD

**Issue by connesy** [sindresorhus/notifier-for-github#220]
Version 20.7.6
Despite having internet connection the extension icon still shows "You have to be connected to the internet". When I click on the icon, it works fine and I get taken to github.com/notifications.

![Screenshot from 2020-07-07 09-34-04](https://user-images.githubusercontent.com/13164166/86738305-41534f80-c035-11ea-8fea-8e51668e4580.png)

I have tried closing and opening Google Chrome, disabling and enabling the extension, and turning my internet connection off and on.

**Comment by notlmn** [comment]
This is a long standing issue from Chrome, and is already being tracked by #132. Apparently this is not an issue with Firefox, and seen only in Chrome.

This does seem to be bit different, can you try disabling and re-enabling the extension.

**Comment by connesy** [comment]
That didn't work.

**Comment by notlmn** [comment]
Can you try uninstalling the extension and installing it again, using a fresh personal access token? I'm trying to see why this keeps failing very inconsistently.

**Comment by connesy** [comment]
I've now uninstalled and re-installed the extension using a newly generated personal access token with `repo` and `notifications` permissions. The problem still persists.

**Comment by notlmn** [comment]
Can you help me inspect this by

- Navigating to `chrome://extensions`
- Click on "background views" for this extension
- Check for any errors in console tab

**Comment by connesy** [comment]
I get these errors:

![image](https://user-images.githubusercontent.com/13164166/87013399-ddfb2600-c1ca-11ea-8f00-490b8b05a594.png)

**Comment by notlmn** [comment]
I think that you have "Root URL" option set to `https://github.com` instead of `https://api.github.com`. This limitation would be completely removed when #219 gets resolved. For now you have to use `https://api.github.com`.

**Comment by connesy** [comment]
You are right, that was it. Thanks!
