### ISSUE TITLE
Feature Request: Github Actions status notifications

### ISSUE THREAD

**Issue by Absolucy** [sindresorhus/notifier-for-github#223]
Would be useful: some of my github actions can take hours, and I would just rather have a notification telling me whether they passed or failed rather than babysitting them.

**Comment by notlmn** [comment]
AFAIK there is no GitHub API that lets us listen on GitHub actions or even as basic as listing all of the active ones.

Unless GitHub provides status of Workflow runs as notifications. /cc @lukehefson

For now I'd leave this out to extensions like "Refined GitHub" which already has a similar discussion already going on at https://github.com/sindresorhus/refined-github/issues/2427.

**Comment by notlmn** [comment]
Or you can use something like https://github.com/marketplace/actions/send-email to receive email notifications.

**Comment by Absolucy** [comment]
@notlmn This exists: https://github.com/abskmj/hukum

https://developer.github.com/v3/actions/

**Comment by notlmn** [comment]
`hukum` works on a per-repository basis, that is the only way you query the API. There is no API that allows you to get all running actions of a user in a single request (like `/notifications`), this is what I meant the following statement.

> or even as basic as listing all of the active ones.

For this to work, we have to query actions for each repository the user has access to individually every minute. Which could end up being in the hundreds of requests every minute, which is not ideal.

**Comment by Absolucy** [comment]
Oof, makes sense. I just wanted to stop having to babysit [Rust-iOS-Nightlies ](https://github.com/luxxxxy/Rust-iOS-Nightlies) builds, which can easily take 3-4 hours.

**Comment by notlmn** [comment]
For your use-case you should really try `send-email` action, which would be way reliable than any other hack build on top of GitHub UI.
