### ISSUE TITLE
Icon left click popop

### ISSUE THREAD

**Issue by pasha-zzz** [sindresorhus/notifier-for-github#226]
Maybe optionally, when I click on icon and unread notifications count > 0, display list of unread notifications (clickable) in popup without opening separate tab for all notifications?
And I can click on any unread notification in this popup to go to it directly.
And in top of this popup you can place link "Notifications on Github".

Something like this:
![image](https://user-images.githubusercontent.com/8224786/88894734-02d63c80-d251-11ea-8058-69784b4c613f.png)

**Comment by notlmn** [comment]
Duplicate of #216
