### ISSUE TITLE
More accurate notification reasons

### ISSUE THREAD

**Issue by amaisano** [sindresorhus/notifier-for-github#227]
Just one example:

I have been requested for a PR review. I get:

![image](https://user-images.githubusercontent.com/688435/88931577-036bd480-d24b-11ea-9583-5a3ddcf450ed.png)

I make my review, and request changes.

The other developer comments on one of my change requests comments, and I get, well, the same exact thing:

![image](https://user-images.githubusercontent.com/688435/88931643-19799500-d24b-11ea-85b0-13271d08cd96.png)

I would have expected the reason (second line) to be:

```js
    comment: 'New comment',
```

Is this a GitHub level limitation or can we know the difference in the extension?

**Comment by notlmn** [comment]
Yes, this a GitHub limitation.

You can also see this behavior in GitHub's notifications UI too, for the exact same notification.
