### ISSUE TITLE
Desktop notifications play a sound despite the setting being disabled

### ISSUE THREAD

**Issue by eboddington** [sindresorhus/notifier-for-github#231]
In the Notifier for GitHub settings, I have "enable notification sound" unchecked.

When a desktop notification is sent, it still plays a sound.

Notifier for GitHub 20.9.10
Firefox 81.0.1
macOS 10.15.7

**Comment by notlmn** [comment]
Can you try enabling and disabling it again, this usually happens when you have settings synced form a device that you have allowed notifications on, to a device that still doesn't have notifications permission granted.

We do not modify the settings in that case, as it would mess up notification preferences on the other device.

**Comment by eboddington** [comment]
Hm, I've tried enabling (then closing the preferences - not sure at which point the preference is saved), and then disabling again but the sound is still playing. I haven't installed the plugin on any other devices.

**Comment by notlmn** [comment]
Curious if disabling and enabling the extension helps, and along with toggling checkboxes again?

Also is this the first time you have the extension installed, or is this a new issue for you.

**Comment by eboddington** [comment]
I tried disabling and enabling the extension, then enabling and disabling the checkbox. I also tried disabling and enabling the "desktop notifications" option, followed by the sounds option.

This is the first time I've installed the extension, either on this system/browser or any other!

I think it seems to have turned off now :)

Feel free to close this, and I can reopen if I realise that it's still playing sounds.

**Comment by eboddington** [comment]
Nope, still getting them! Not sure if they actually stopped yesterday or I just somehow failed to notice :(

**Comment by notlmn** [comment]
Hey @eboddington, if you try to open `about:debugging#/runtime/this-firefox` in Firefox, and click "Inspect" for this extension in there, you should be able to run `await browser.storage.sync.clear()` in the "Console" tab.

After this, can you disable and enable the extension again and see if that works?

**Comment by eboddington** [comment]
@notlmn done - I ran that, disabled and enabled the extension, set my preferences again since they had been cleared, and I'm getting the sounds on notifications still. Also tried enabling and disabling the notification sounds in the preferences, but they're still persisting.

**Comment by fregante** [comment]
Why does the extension play the sound manually instead of letting the notification API deal with it? There’s a `silent` toggle: https://developers.chrome.com/docs/extensions/reference/notifications/

Edit: I suppose this is because you have 2 separate toggles for notifications and sounds.

**Comment by notlmn** [comment]
Chrome/Firefox is playing a notification sound as that's the default behavior. The behavior we have documented here is working as expected.

Chrome/Firefox used to show a custom notification popup on the screen, on modern OS' the UA's use native notification helpers and that plays sound based on system settings.

- Turn off notifications inside the extension options if you don't want our sound to be played.
- Turn off notifications for Chrome/Firefox at a system level to not get any notification sound.
