### ISSUE TITLE
Notification count is sometimes stale

### ISSUE THREAD

**Issue by zubin** [sindresorhus/notifier-for-github#233]
Not sure what circumstances cause this, but I've noticed that sometimes the notification count doesn't get updated. 

The only way I've found to correct it is to toggle the extension off then on. 

Some ideas to resolve this:

- Add an option to periodically poll for the count (eg every minute; 5/15 minutes; or hour). 
- Add a link to "force refresh" the counts.

**Comment by fregante** [comment]
I noticed that background.js creates and clears alarms all the time. The Alarms API lets set repeating alarms, maybe you should just let it handle it autonomously, only clearing/resetting them if the user changes the interval.

**Comment by notlmn** [comment]
Closing as stale bug, not reproducible.
