### ISSUE TITLE
Open 10 tabs when clicking notification in Mac OS Big Sur / Firefox

### ISSUE THREAD

**Issue by JulienGenoud** [sindresorhus/notifier-for-github#234]
MacOS open 10 new tab for the same page when I receive and clicking on a notification,

OS : Mac OS Big Sur
Browser : Firefox.

any idea ?

**Comment by fregante** [comment]
This is likely because `addHandlers` is called multiple times indiscriminately. 

Also `permissions.onAdded` is no longer Chrome-specific. It’s been in firefox for a while.

**Comment by wdsrocha** [comment]
Same thing happening on macOS Catalina 10.15.2 with Google Chrome 87.0.4280.141 :-(

**Comment by wdsrocha** [comment]
Update: the bug stopped like 2 days ago, but I don't know why.

**Comment by GuilleDF** [comment]
I just installed this extension from the chrome web store and I can confirm it's happening
macOS Catalina 10.15.7 & Chrome 88.0.4324.96
Extension version: 20.9.10

**Comment by ElijahLynn** [comment]
Just installed fresh today and am getting 5 new tabs on Arch Linux (Gnome) and Brave. 


1.18.78 Chromium: 87.0.4280.141 (Official Build) unknown (64-bit)
