### ISSUE TITLE
Show notification shelf

### ISSUE THREAD

**Issue by acomagu** [sindresorhus/notifier-for-github#237]
The top bar we can see on issue/pull page when I jump from [github.com/notifications](https://github.con/notifications)(seems to be called "notification shelf") is not shown if we jump by clicking desktop notification from this extension.

![Screenshot_20201230_073821](https://user-images.githubusercontent.com/1362750/103318947-67512e00-4a73-11eb-876e-67c701a8afac.png)

The buttons are useful to operate the notification quickly.

**Comment by acomagu** [comment]
I noticed it's shown if I attach `notification_referrer_id` query param, like `https://github.com/sindresorhus/notifier-for-github/issues/1?notification_referrer_id=FOO`. But I couldn't find out the ID in GitHub API. I guess scraping may be the only way to do currently 😕

**Comment by notlmn** [comment]
Yup, GitHub uses a bunch of tricks like `notification_referrer_id` and other parameters to show that shelf if you are opening from the GitHub notifications page.

There's a lot of stuff in UI that is not available in API, and some stuff that we try to guess in this codebase.

The notification I received for this has `notification_referrer_id` as `MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE0MzgwMDQ5NDQ6Mzc3Njk5NzQ=`, which decodes from base64 to `018:NotificationThread1438004944:37769974`, a bunch of internal stuff that is not exposed in any way.

Also we don't have access to page content to do scraping :D
