### ISSUE TITLE
I would like to contribute!

### ISSUE THREAD

**Issue by SteveSajeev** [sindresorhus/notifier-for-github#240]
I would like to contribute to this awesome extension. I forked and cloned my repo but when I try to load the source folder to chrome, it says: 
```
Could not load background script 'browser-polyfill.min.js'.
Could not load manifest.
```
Please correct me if I loaded the wrong folder.

**Comment by notlmn** [comment]
Looks like we are missing a `contributing.md` file to make it easier for people to build, install, and test extension locally.

You'll have to have Node.js and npm installed, then run `npm install` and `npm run build` to end up with a directory called `distribution` which is the directory that gets published to extension stores.

This is also the directory that you load into Chrome/Firefox to test locally, not the `source` directory.

Again, thanks for thinking of contributing.

**Comment by SteveSajeev** [comment]
Thank you very much! Yeah, I think there can be a ```contribution.md``` file. Thanks for the time.

**Comment by SteveSajeev** [comment]
Sorry for asking again and again in the same issue.
Will I need to run ```npm run build``` after I have made changes to source folder.

I am new to contributing, pls correct me if I am wrong.
