### ISSUE TITLE
I made few edits to the extension!

### ISSUE THREAD

**Issue by SteveSajeev** [sindresorhus/notifier-for-github#241]
I have made a simple gui for the extension, I am still working on it. But am I allowed to merge it with your extension if you like. I spent a lot of time. You can view the extension with GUI:
https://github.com/SteveSajeev/notifier-for-github

I hope you liked it :)

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but we don't have any plans to add any GUI.

**Comment by SteveSajeev** [comment]
?-Sorry, mm :(
