### ISSUE TITLE
Notifier opens 3 duplicate tabs [firefox]

### ISSUE THREAD

**Issue by xtuchyna** [sindresorhus/notifier-for-github#242]
Whenever clicking on Notifier when 1 new notification present, it opens three duplicate tabs at once.
Happens on Firefox 79.0 (64-bit), Fedora 32

Issue similar to #234

**Comment by ElijahLynn** [comment]
I am getting 5 notifications on Arch Linux (Gnome) and Brave browser.

**Comment by xtuchyna** [comment]
Issue resolved in time, don't know what caused it. Closing
