### ISSUE TITLE
New GitHub tokens are not accepted by the options form

### ISSUE THREAD

**Issue by fregante** [sindresorhus/notifier-for-github#244]
Not a bug yet, but soon it will be:

https://github.blog/changelog/2021-03-04-authentication-token-format-updates/

The new format isn't accepted by our form

**Comment by czuniga-xtages** [comment]
FWIW, I just installed the extension and it's rejecting the token I just generated.

**Comment by patspam** [comment]
Are there any workarounds for new users?

**Comment by jef** [comment]
> Are there any workarounds for new users?

Wait :)

**Comment by Levi-Lesches** [comment]
@sindresorhus any word on when a new version will be released?

**Comment by sindresorhus** [comment]
The automatic release is scheduled for tomorrow evening: https://github.com/sindresorhus/notifier-for-github/blob/31a172007453789ee93427efb10ee7138073dcf7/.github/workflows/release.yml#L9

I don't remember how to force push a release. @fregante ?

**Comment by fregante** [comment]
Refer to the new collaborators file on Refined GitHub (PR). Or go to Actions -> Release -> Run Workflow

**Comment by sindresorhus** [comment]
Hmm, seems the release workflow has been failing for some time now: https://github.com/sindresorhus/notifier-for-github/runs/2236891461?check_suite_focus=true

// @notlmn

**Comment by sindresorhus** [comment]
An update has been submitted. Now just waiting for Firefox/Google to review and publish it.

**Comment by sindresorhus** [comment]
The update is out now for Chrome: https://chrome.google.com/webstore/detail/notifier-for-github/lmjdlojahmbbcodnpecnjnmlddbkjhnn

(It will probably take a couple of hours to propagate)

**Comment by bjeanes** [comment]
Thanks! While not stated, the FireFox add-on has also been updated and works great. Thank you for quick turnaround!

**Comment by muuvmuuv** [comment]
Is a release for web-stores already in the pipeline? My Chrome version seems still behind as far I can tell from GH releases.
