### ISSUE TITLE
Error: missing token (new token format)

### ISSUE THREAD

**Issue by RafaelKr** [sindresorhus/notifier-for-github#248]
After updating to 21.4.6 (Firefox) we can set the new token but it cannot be used due to this check:

https://github.com/sindresorhus/notifier-for-github/blob/c9c66fe81df2767eb8ec705cba3d3f066728583b/source/lib/api.js#L44-L46

**Comment by sindresorhus** [comment]
// @fregante

**Comment by RafaelKr** [comment]
This should fix it: `ghp_\w{36,251}|[a-z\d]{40}`

https://regex101.com/r/yMMKp9/1

I'll do a PR.

**Comment by sindresorhus** [comment]
I have removed that check for now and published another version.

**Comment by sindresorhus** [comment]
> I'll do a PR.

👍

**Comment by RafaelKr** [comment]
PR is ready
#249

**Comment by sindresorhus** [comment]
The new update is now published and available in the Chrome store.

**Comment by RafaelKr** [comment]
Nice! I now get notifications again :partying_face: 
Thanks for this great plugin!
