### ISSUE TITLE
Chimes for no reason every 36 seconds

### ISSUE THREAD

**Issue by abrahammurciano** [sindresorhus/notifier-for-github#255]
When this extension is enabled, and there are unread Github notifications, I get a chime every 36 seconds. After I mark them all as read, the chime stops.

Expected behaviour: It should chime once, when each notification is created, but not after that.

OS: Arch Linux, kernel 5.11.15-arch1-2
Chrome: Version 90.0.4430.72 (Official Build) (64-bit)

**Comment by superbogy** [comment]
same to me. Make me crazy and forbid the extension

**Comment by superbogy** [comment]
Does this repo still in maintenance?

**Comment by IPWright83** [comment]
I've got exactly the same issue on Ubuntu 20.04. I've been trying for ages to determine what the cause was. Mine isn't quite so frequent as every 36 seconds though!

**Comment by elldritch** [comment]
This is happening to me too.
