### ISSUE TITLE
Notification doesn't work: `icon-notif.png` is missing in distribution

### ISSUE THREAD

**Issue by andylizi** [sindresorhus/notifier-for-github#259]
Packaged extension doesn't have `icon-notif.png` file in it, causing `file not found` error to be thrown when displaying notifications.

https://github.com/sindresorhus/notifier-for-github/blob/f1facf697f07bc01a030da358c953e4df0155127/source/lib/notifications-service.js#L102

Running `npm run build` will output:
```
√ Built in 7.08s

distribution\manifest.json               787 B     82ms
distribution\icon.png                  1.24 KB     81ms
distribution\icon-toolbar.png            553 B     82ms
distribution\background.js           103.58 KB    112ms
distribution\options.html              2.64 KB    188ms
distribution\options.5e2d4b3a.css         4 KB    191ms
distribution\options.f5a2a783.js      92.91 KB    191ms
```

**Comment by notlmn** [comment]
@fregante, #252 removed `CopyWebpackPlugin` in webpack, is there a way to move the rest of the files using Parcel?

**Comment by fregante** [comment]
Either `chrome.runtime.getURL` or `web_accessible_resources` will cause Parcel to include the path.

Docs: https://v2.parceljs.org/recipes/web-extension/#asset-urls

**Comment by andylizi** [comment]
This seems to be fixed.
