### ISSUE TITLE
No sound/desktop notification on MacOS + Chrome

### ISSUE THREAD

**Issue by bramjoosten** [sindresorhus/notifier-for-github#262]
Expected a popup of some kind and/or sound.

The extension is set up correctly to my knowledge, since it shows the number of unread notifications, and I gave all permissions. If there's anything I misconfigured let me know. I'm also happy to help updating the readme after it's fixed.

**Comment by bnjns** [comment]
I've had this problem for a while too. I can confirm that Chrome is able to show desktop notifications (as other extensions work), and I've tried removing and reinstalling the extension, and checking the permissions. I'm having to resort to using a minimised Firefox window just for desktop notifications 😂

**Comment by amaisan0** [comment]
Same problem. This used to work fine for me. However when I created a new Chrome profile and installed this extension fresh on there, I get little [1] numbers on the extension icon, but NO DESKTOP NOTIFICATIONS OR SOUNDS, even when those settings are enabled in the extension options. Please help!

- MacOS Big Sur 11.6
- Chrome Version 94.0.4606.71 (Official Build) (x86_64)
- Notifier for GitHub 21.9.15

![image](https://user-images.githubusercontent.com/85192138/137198478-e7ae7565-4298-4f84-a339-bd6407c7a10c.png)

**Comment by fatih-celonis** [comment]
I'm having the same issue with the setup as well.

**Comment by jameskerr** [comment]
Same here

**Comment by notlmn** [comment]
Hey folks, sorry about [the long pause](https://en.wikipedia.org/wiki/Polynesia#:~:text=referred%20to%20as-,the%20long%20pause,-between%20the%20first) on this bug.

Found that this issue is due to missing `icon-notif.png` in the CRX file that Chrome gets, Firefox doesn't bother if it can get this file or not, but Chrome errors out trying to load this file.

``` bash
❯ unzip -l extension.crx
Archive:  extension.crx
warning [extension.crx]:  1061 extra bytes at beginning or within zipfile
  (attempting to process anyway)
  Length      Date    Time    Name
---------  ---------- -----   ----
   106066  11-17-2021 12:33   background.js
      553  11-17-2021 12:33   icon-toolbar.png
     1272  11-17-2021 12:33   icon.png
      857  11-17-2021 12:33   manifest.json
     4101  11-17-2021 12:33   options.5e2d4b3a.css
    95143  11-17-2021 12:33   options.f5a2a783.js
     2699  11-17-2021 12:33   options.html
        0  11-17-2021 12:33   _metadata/
     1817  11-17-2021 12:33   _metadata/verified_contents.json
---------                     -------
   212508                     9 files
```

``` bash
❯ unzip -l notifier_for_github-21.11.17-an+fx.xpi
Archive:  notifier_for_github-21.11.17-an+fx.xpi
  Length      Date    Time    Name
---------  ---------- -----   ----
   106066  00-00-1980 00:00   background.js
      553  00-00-1980 00:00   icon-toolbar.png
     1272  00-00-1980 00:00   icon.png
      790  00-00-1980 00:00   manifest.json
     4101  00-00-1980 00:00   options.5e2d4b3a.css
    95143  00-00-1980 00:00   options.f5a2a783.js
     2699  00-00-1980 00:00   options.html
     1111  00-00-1980 00:00   META-INF/cose.manifest
     3110  00-00-1980 00:00   META-INF/cose.sig
     1432  00-00-1980 00:00   META-INF/manifest.mf
      144  00-00-1980 00:00   META-INF/mozilla.sf
     4357  00-00-1980 00:00   META-INF/mozilla.rsa
---------                     -------
   220778                     12 files
```

Seeing this issue after #252 and is possibly Parcel related. The `source/manifest.json` file has `"icon-notif.png"`, while `distribution/manifest.json` has `"/icon-notif.png"` for `web_accessible_resources` field, after Parcel's processing. The resulting CRX and XPI files (downloaded from respective webstores) don't have the file included at all.

@fregante any idea about this, on how to let Parcel not modify these URLs?

**Comment by fregante** [comment]
You can specify the file in "web accessible resources" in the manifest. Refer to MDN for the format. Parcel will pick up all the files/folders listed in there.

**Comment by notlmn** [comment]
I apparently had changes made locally for fixing this a while ago, but couldn't get to submit changes.

Just made changes, pushed, and released a new version `22.1.3`, that I tested to work on Chrome on macOS. Enabled developer mode in `chrome://extensions` and do a force update to make sure you are on the latest version.

**Comment by fregante** [comment]
\* 22.* 😃

**Comment by jameskerr** [comment]
This is now working for me. Thank you! My 2022 is off to a great start.
