### ISSUE TITLE
support to set proxy for API server

### ISSUE THREAD

**Issue by tjx666** [sindresorhus/notifier-for-github#265]
![image](https://user-images.githubusercontent.com/41773861/146231011-86a95b78-cb23-46f1-ad0f-46217cf782dd.png)

**Comment by sindresorhus** [comment]
Every single Chrome extension should not need to do this. We are using `window.fetch` for requests. I assume Chrome supports proxies for that. So you need to correctly define your proxy settings in Chrome.
