### ISSUE TITLE
Not Able To Start The project with npm start

### ISSUE THREAD

**Issue by ghost** [sindresorhus/notifier-for-github#266]
Hey , I am madhav and i  have clone your project into my local machine and after running npm install but when i run npm start
it is showing many error
![Screenshot (5)](https://user-images.githubusercontent.com/68507755/150478056-c4c564d8-2637-4c22-9a41-2fe8fbc4bcfb.png)
s

Please Help To Fix This .

**Comment by sindresorhus** [comment]
This is not a support forum.
