### ISSUE TITLE
Email sending not working

### ISSUE THREAD

**Issue by dima-ogrenich** [sindresorhus/notifier-for-github#269]
Description
I have created a trigger and messages, but the send is not working. The application email is configured by SMTP.

Steps to reproduce

1. Сreated a trigger;
2. Configured for save all entries;
3. Сreated a message with template;
4. I don't receive emails.

Plugin version: 2.2.4
Craft version: Pro 3.7.43
Multi-site: Yes
PHP version: 7.4.29
Email Transport Type: SMTP
Database driver & version: MySQL 5.5.5

**Comment by sindresorhus** [comment]
Wrong repo
