### ISSUE TITLE
Desktop notifications are not sent

### ISSUE THREAD

**Issue by mabrikan** [sindresorhus/notifier-for-github#276]
Extension version: 23.2.15
Firefox version: 110.0
OS: Manjaro Linux. Kernel: 6.0.19

This is happening recently. Everything is working fine and I can see notifications count in the icon. Only problem is with sending desktop notifications, even though it is enabled in the settings.

I thought this is an issue with Firefox or my current configuration, but then I tested sending a desktop notification using this extension (https://addons.mozilla.org/en-US/firefox/addon/notification-test/) and it is working fine.

**Comment by alejogtz** [comment]
Same issue on Chrome
OS: Windows 11 Pro x64 (build: 22621)
Chrome Versión 110.0.5481.105 (Build oficial) (64 bits)
