### ISSUE TITLE
Random notification chime every minute or so

### ISSUE THREAD

**Issue by pgivel** [sindresorhus/notifier-for-github#278]
Starting this morning I've had random notification chimes play, without any notification showing, around every minute or so. I have tried revoking notification permissions as well as muting every open tab until I found the culprit, being Notifier for Github. Unchecking the "Enable notification sound" checkbox in the extension settings allows me to not have the sound, but I'd like to have it when there's a legitimate notification.

I'm using Chrome Version 111.0.5563.65 (Build officiel) (64 bits) on Windows 10.

I have seen [this issue](https://github.com/sindresorhus/notifier-for-github/issues/255) and [that fix](https://github.com/sindresorhus/notifier-for-github/pull/275) but I guess it broke again ?

Since it seems related to the locale & time, I am located in Paris, France, using a french locale.

**Comment by MrMazzone** [comment]
Driving me crazy all day!

**Comment by pylafleur** [comment]
Same problem here, it started today. When I'm doing nothing, the sound plays every minute. However, navigating on Github seems to trigger the sound much more frequently. Disabling notification sound made it stop.

I'm on MacOS, Chrome 110.0.5481.177 (Official Build) (x86_64). Also, I'm in Canada (EST).

Edit: I’ve had unread notifications while this was happening.

**Comment by charliegroll** [comment]
MacOS 13.2.1, Firefox Developer 111.0b8 checking in - also drove me crazy all day

**Comment by mabrikan** [comment]
I think I was able to reproduce it. This happens to me **only** when I disable notification permission.

I think its a bug. I'm working on a fix PR.
