### ISSUE TITLE
Enable Dependabot and CodeQL security 

### ISSUE THREAD

**Issue by neatcoder** [sindresorhus/notifier-for-github#285]
Enabling [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates) and keeping a check on code vulnerabilities using [CodeQL](https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning-with-codeql) can make this app more trustworthy and makes a strong case for approval by any company that wishes to allow their users to enable it

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but I'm not interested in enabling these.

**Comment by Malix-Labs** [comment]
?
