### ISSUE TITLE
Notification doesn't goes of on Deepin 20

### ISSUE THREAD

**Issue by eduardomozart** [sindresorhus/notifier-for-github#287]
Hello,
I use this extension on my macOS Monterey and on Deepin 20.9 (based on Debian 10). On macOS it seems to be working as expected: when I receive a notification, I click on it, read it on GitHub and it vanishes from the Notfier for GitHub button. But on Deepin it don't happen. I have to close the browser and open it again for it to mark a notification as read.
Please let me know if I can provide any information to troubleshoot this issue.

**Comment by notlmn** [comment]
I would go out on a limb to say that Deepin is not supported and is very hard to for us to troubleshoot and see what's happening.
