### ISSUE TITLE
Convert to GitHub App

### ISSUE THREAD

**Issue by Malix-Labs** [sindresorhus/notifier-for-github#289]
See [GitHub Docs - Choosing between a GitHub App or a personal access token](https://docs.github.com/en/apps/creating-github-apps/about-creating-github-apps/deciding-when-to-build-a-github-app#choosing-between-a-github-app-or-a-personal-access-token)

**Comment by fregante** [comment]
Apps have limited access to notifications, most [notification endpoints](https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28) are marked as:

> This endpoint does not work with GitHub App user access tokens, GitHub App installation access tokens, or fine-grained personal access tokens.
