### ISSUE TITLE
Landing Page Customization?

### ISSUE THREAD

**Issue by shawnwildermuth** [sindresorhus/notifier-for-github#292]
Any way to have the notification take me to the "Inbox" instead of "Participating"? Am I missing a setting?

**Comment by notlmn** [comment]
If you have the option under "Participating Count" set in your extension options, you will only get notifications for what you are participating in and the extension takes you to that page instead of inbox.

**Comment by shawnwildermuth** [comment]
Ah, I had that turned on, didn't realize that's why it *didn't* take me to the issues. Thanks for the fast response.
