### ISSUE TITLE
URGENT: Manifest v3

### ISSUE THREAD

**Issue by Malix-Labs** [sindresorhus/notifier-for-github#297]
# **Urgent**

The extension will soon be unusable on Chromium due to the deprecation of Manifest v2

![image](https://github.com/user-attachments/assets/ba7aa5fe-524c-4534-93d3-cbe34f362ab1)

It needs to make the transition to Manifest v3

**Comment by notlmn** [comment]
I have a draft at #298, but Firefox doesn't support `offscreen` permission yet which is needed to play audio as part of manifest v3.

**Comment by Malix-Labs** [comment]
@notlmn thanks for the notice!

Can you [link that issue to the pull request](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) please?

**Comment by niu541412** [comment]
Firefox still supports manifest v2 and seems to have no plan to drop it. So keeping the version unchanged in the Firefox add-on store is ok. 
> I have a draft at #298, but Firefox doesn't support `offscreen` permission yet which is needed to play audio as part of manifest v3.

**Comment by Malix-Labs** [comment]
> I have a draft at https://github.com/sindresorhus/notifier-for-github/pull/298

Very nice !

> but Firefox doesn't support offscreen permission yet which is needed to play audio as part of manifest v3.

The biggest threat is that the extension will be automatically force uninstalled when chrome will drop manifest v2 support, so a manifest v3 **has** to be published before that to not drop a huge proportion of its userbase

**Comment by subdavis** [comment]
FWIW, I've seen many extension developers have separate build configs for chrome and ff.  I recently upgraded an extension to mv3 while leaving firefox as v2.  Here's my manifest generation file: https://github.com/subdavis/Tusk/blob/main/scripts/manifest.ts

**Comment by Malix-Labs** [comment]
>I've seen many extension developers have separate build configs for chrome and ff

Indeed

See [the top 3 tools comparison](https://wxt.dev/get-started/compare.html)
