### ISSUE TITLE
Use `chrome.storage.sync` instead of `localStorage`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/notifier-for-github#39]
It syncs and supports more types than just strings, so we can simplify the code a bit.

Example usage: https://developer.chrome.com/extensions/optionsV2#step-2
Docs: https://developer.chrome.com/extensions/storage

**Comment by Narno** [comment]
"storage.sync" or "storage.local"? :)

https://developer.chrome.com/extensions/storage#using-sync

**Comment by sindresorhus** [comment]
`storage.sync`

**Comment by Narno** [comment]
I thinks we should let user choose the storage area (local or "sync").

**Comment by Narno** [comment]
WIP, please checks the [dedicated branch](https://github.com/sindresorhus/github-notifier-chrome/tree/feature-39-chrome.storage.sync).

**Comment by sindresorhus** [comment]
Do a PR ;)

**Comment by Narno** [comment]
I should fixes some problems before, introduced by the asynchronous logic of chrome storage methods.

**Comment by sindresorhus** [comment]
PRs doesn't have to be finished. Just easier to review than looking at a fork branch.

**Comment by Narno** [comment]
Yes, it sound good. I will do that today.

**Comment by YurySolovyov** [comment]
I'm thinking of picking that up.
There is a question about migrating local storage values: do we really want it? I noticed a to-do in @Narno PR, but it was not finished.

**Comment by sindresorhus** [comment]
@YurySolovyov Yes, should be easy: https://github.com/sindresorhus/notifier-for-github-chrome/pull/42#issuecomment-142986917

**Comment by Narno** [comment]
> I'm thinking of picking that up.

\o/

Be careful: my code is very old and is decorrelated from the main branch.

**Comment by YurySolovyov** [comment]
@Narno notice that I'm going to pick up an issue, not a PR :)

**Comment by YurySolovyov** [comment]
Note to self:
>```
Drop storage lookup in PermissionsService and only use
chrome.permissions.contains
to check permissions
```

**Comment by YurySolovyov** [comment]
This should be much easier with `async / await` shipped in Chrome 55

**Comment by Narno** [comment]
And we can consider my previous work totally outdated! :-)

**Comment by sindresorhus** [comment]
I think we can make it even simpler by moving to a good module for this, see https://github.com/sindresorhus/notifier-for-github-chrome/issues/147
