### ISSUE TITLE
debugging 'unknown error'

### ISSUE THREAD

**Issue by saelfaer** [sindresorhus/notifier-for-github#54]
Hi, I recently started getting 'unknown error' with a questionmark in the label over the notifier icon.
I have no clue where to look for more detailed information so I can either fix it or update you guys with a more precise problem to fix :)

any ideas on where to look or how to debug this thing?

**Comment by YuriSolovyov** [comment]
@saelfaer 
The "Unknown error" comes from [switch statement in `main.js`](https://github.com/sindresorhus/notifier-for-github-chrome/blob/master/extension/main.js#L44)
That would be a place to start I guess.

**Comment by GRA0007** [comment]
I'm getting this error too, and my api key is definitely correct.

**Comment by Matsv** [comment]
Also happens for me every time my pc boot up again from sleep mode. I have to click on the icon before it starts checking again.

**Comment by GRA0007** [comment]
Ah that makes sense. I have a laptop so I'm constantly putting it in sleep mode. It would be nice if this error could be fixed though.
