### ISSUE TITLE
Use chrome.identity.launchWebAuthFlow to get an OAuth token

### ISSUE THREAD

**Issue by ImJasonH** [sindresorhus/notifier-for-github#57]
https://developer.chrome.com/apps/identity#method-launchWebAuthFlow

```
var CALLBACK_URL = 'https://'+chrome.runtime.id+'.chromiumapp.org';
var AUTH_URL = 'https://github.com/login/oauth/authorize/?client_id='+CLIENT_ID+'&redirect_uri='+CALLBACK_URL+'&scope=notifications';
...
// Opens a window to initiate GitHub OAuth, fires callback
// with token in the URL.
chrome.identity.launchWebAuthFlow({
  url: AUTH_URL,
  interactive: true,
}, function(redirectURL) {
  var q = redirectURL.substr(redirectURL.indexOf('#')+1);
  var parts = q.split('&');
  for (var i = 0; i < parts.length; i++) {
    var kv = parts[i].split('=');
    if (kv[0] == 'access_token') {
      token = kv[1];
      console.log('token is', token);
    }
  }
});
```

This would remove the need for users to generate a personal access token and copy/paste it in themselves.

**Comment by sindresorhus** [comment]
:+1: Didn't know that was possible. Wanna do a pull request?

Use https://github.com/sindresorhus/query-string to get the query parameter. Browser version here: https://wzrd.in/standalone/query-string

**Comment by YurySolovyov** [comment]
@ImJasonH what's `CLIENT_ID` in this case?

**Comment by ImJasonH** [comment]
You can get a client ID by creating credentials for your project in the [Google Developers Console](https://console.developers.google.com/apis/credentials). Click "Create credentials" then select "OAuth client ID"

**Comment by YurySolovyov** [comment]
@sindresorhus any thoughts? I might take a look at implementing this, but I think getting `CLIENT_ID` is available for extension owner only.

**Comment by sindresorhus** [comment]
`CLIENT_ID` → `1053844927102-lb8knf98gq6o26bu4v5a3kpqpapj6tkl.apps.googleusercontent.com`

**Comment by YurySolovyov** [comment]
@sindresorhus thanks, obviously blocked by #90 for now

**Comment by sindresorhus** [comment]
#90 is now merged, finally ;)

**Comment by YurySolovyov** [comment]
I'll see what I can do :)

**Comment by ExE-Boss** [comment]
You will also need to consult [GitHub’s OAuth Apps documentation](https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/) and register [this extension with GitHub](https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/registering-oauth-apps/).

**Comment by notlmn** [comment]
Closing this because of the issues mentioned in https://github.com/sindresorhus/notifier-for-github/pull/166#issuecomment-443150825

**Comment by imjasonh** [comment]
The `launchWebAuthFlow` API removes the need to ask for `https://*/*` permission, AIUI.

Instead, calling that opens a small Chrome window that can only go through OAuth flows and post back the resulting auth token. So unless I'm misunderstanding the issue with #166, you should still be able to use `launchWebAuthFlow`.

**Comment by notlmn** [comment]
> The `launchWebAuthFlow` API removes the need to ask for `https://*/*` permission, AIUI.

Yes, `launchWebAuthFlow` does not need the special permission, but you only get OAuth code (`code`) in this flow, not the actual OAuth Access Token (`access_token`). For that you have to exchange this `code` with GitHub for an `access_token`.

This requires a fetch request to the GitHub server from the extension, which would error out because of CORS, i.e., the browser will not let you access non-CORS response without having permission granted to that site.

**Comment by ExE-Boss** [comment]
But that should only require a permission for https://api.github.com.

**Comment by notlmn** [comment]
> But that should only require a permission for [api.github.com](https://api.github.com).

Yea, and also we need `https://*/*` to support all possible GitHub enterprise domains too, dynamic permission requests.

__Edit__: api.github.com already has `Access-Control-Allow-Origin` header set to `*`, it is `github.com` (or the enterprise domain name) that doesn't have the header set and require extension permission to bypass.

**Comment by ExE-Boss** [comment]
Well, that can just be an optional permission, right?

You could also keep the old way for enterprise installs.

**Comment by notlmn** [comment]
> Well, that can just be an optional permission, right?

I already did that, the code is almost complete and is at https://github.com/notlmn/notifier-for-github/tree/identity-flow.

I closed it because it was making the extension more complex by adding more code to an otherwise simple extension.

And the other reason being adding additional permissions, which were recently removed in #161, and people were getting [concerned](https://github.com/sindresorhus/notifier-for-github/pull/162) about it.

**Comment by imjasonh** [comment]
I'd still love to have this. I could really use a notifier extension, and I don't feel comfortable generating a PAT for it. I only use github.com.

If anybody is reading this and is interested in moving this forward, I would love to make it happen. @notlmn's [changes](https://github.com/sindresorhus/notifier-for-github/compare/main...notlmn:notifier-for-github:identity-flow) look fairly straightforward, but they're also dozens of commits behind main now so I have no idea if they would still make sense.
