### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/notifier-for-github#67]
I haven't used this extension for years and it could use an active maintainer that actually cares and can review PRs, triage issues, etc.

**Comment by fstoerkle** [comment]
Hey @sindresorhus,

I would be up for it! I have no experience maintaining an OS project, though.
Would it be possible that you introduce me to some DOs and DON'Ts?

**Comment by Narno** [comment]
> I have no experience maintaining an OS project, though.

![itsatrap](https://cloud.githubusercontent.com/assets/80580/13755327/03cc3e1e-ea1b-11e5-8c43-bb461789e2ae.gif)

Sorry! :stuck_out_tongue:

**Comment by YuriSolovyov** [comment]
I'm up for it as collaborator if possible.

**Comment by gcochard** [comment]
I would be up for it as well.

**Comment by sindresorhus** [comment]
Great! 👌😎🎉

The guidelines are simple. Be kind to everyone. Larger changes should come in a pull request. Smaller ones can be committed directly. Pull requests should have at least one :+1: from another maintainer before being merged. Follow the existing code style and ensure `npm test` passes before pushing a commit.

I'm available for chatting here: https://gitter.im/sindresorhus/meta

@fstoerkle @YuriSolovyov @gcochard Can you add yourself to the `Maintainers` section in the readme?

-

@Narno Happy to list you too in the `Maintainers` section if you want?

**Comment by sindresorhus** [comment]
I'm also looking for maintainers for the [Safari](https://github.com/sindresorhus/notifier-for-github-safari/issues/6) and [Firefox](https://github.com/sindresorhus/notifier-for-github-firefox/issues/15) extension.

**Comment by YuriSolovyov** [comment]
> Can you add yourself to the Maintainers section in the readme?
Done

**Comment by YuriSolovyov** [comment]
@sindresorhus can we have a group for collaborators or something so we can ping everyone like:
/cc @notifier-for-github-chrome/collaborators ?  I saw this in node, but I'm not sure how they did it

**Comment by sindresorhus** [comment]
@YuriSolovyov That's only possible within an organization and only really useful when different users are subscribed to different repos. Here, all maintainers are subscribed to this repo and will get notified regardless.

**Comment by sindresorhus** [comment]
Forgot to mention, when you merge a PR, either ask the contributor to squash their commits before merging or do it for them manually (what I usually do). PRs with lots of irrelevant commits makes the master commit log very noisy ;) (Example: https://github.com/sindresorhus/notifier-for-github-chrome/commit/7d3edf98510c382735f3ece5e2ae58d4f9e38472)

**Comment by YuriSolovyov** [comment]
My bad, sorry.

**Comment by YuriSolovyov** [comment]
@sindresorhus 
> I haven't used this extension for years

Can you tell us why? Just don't need it anymore or extension itself is not good enough?

**Comment by sindresorhus** [comment]
@YuriSolovyov I get too many notifications. I haven't been at zero in a long time.

**Comment by techtonik** [comment]
@sindresorhus my counter is at 2083, and yours?

**Comment by sindresorhus** [comment]
@techtonik It's not that big because I read most of them, but I constantly get new ones, so not really useful to know the number or get desktop notifications about it.

**Comment by techtonik** [comment]
I also have no idea how to deal with desktop notifications - I will be immediately paralyzed trying to react to all those signals.

**Comment by YuriSolovyov** [comment]
@sindresorhus 
With new merge options, whould we always use squash from now on?

**Comment by sindresorhus** [comment]
Yup

**Comment by jacobbearden** [comment]
I'm willing to help with maintaining this if collaborators are still wanted/needed.

**Comment by sindresorhus** [comment]
@jacobbearden Definitely wanted :) @YurySolovyov is doing a great job, but I've been very bad at reviewing his PRs... Would you be willing to review https://github.com/sindresorhus/notifier-for-github-chrome/pull/90 ?

**Comment by jacobbearden** [comment]
Yup :smile:

**Comment by sindresorhus** [comment]
I'm still looking for more maintainers. Happy to add people when you've had a PR merged.

Retweet please: https://twitter.com/sindresorhus/status/988994591129911296 🙌

**Comment by MasterOfTheTiger** [comment]
I would love to help out with this. I have experience with browser extensions. I will have to learn how this one works though.

**Comment by sindresorhus** [comment]
@MasterOfTheTiger Awesome! You could pick an easy issue at first, like https://github.com/sindresorhus/notifier-for-github/issues/149 ;) Let me know if you have any specific questions.

**Comment by Autre31415** [comment]
I've never worked on browser extensions before, though I've considered dabbling in it since the APIs look much nicer these days. Perhaps I'll throw my hat in the ring

**Comment by FadySamirSadek** [comment]
I would also love to help

**Comment by notlmn** [comment]
I would love to help too.

I've already worked on RGH (as @notlmn, previously as @ramlmn).

---------

**Edit**: I've already started working on a refactor [here](https://github.com/sindresorhus/notifier-for-github/compare/master...notlmn:refactor), not yet done but getting there, will submit a PR when done.

**Comment by matheus1lva** [comment]
I would love to help, such a useful extension

**Comment by sindresorhus** [comment]
Closing as @notlmn is doing a good job maintaining this.
