### ISSUE TITLE
Consider adding "Allow querying my tabs" setting

### ISSUE THREAD

**Issue by YurySolovyov** [sindresorhus/notifier-for-github#71]
This came from [discussion](https://github.com/sindresorhus/notifier-for-github-chrome/pull/66#issuecomment-199005768) in #66

ATM, there is no way for user to grant `tabs` permission once it was disallowed, but it could happen by mistake and there is no way to recover other than re-installing extension.

**Comment by techtonik** [comment]
If you're gonna add a setting, make sure that it is user level like "Open notifications in a new window"

**Comment by YuriSolovyov** [comment]
Yeah, I'm ok with choosing other title, ideas are welcome
