### ISSUE TITLE
Multiple Sources for notifications

### ISSUE THREAD

**Issue by wenlock** [sindresorhus/notifier-for-github#73]
Hi, Great extensions!   Just found it and I'm trying it out.   Does it support multiple notification sources such as being able to query the public notification api's as well as a private github enterprise environment at the same time?  Trying to figure out how to make it do that.

**Comment by gcochard** [comment]
This is currently not supported. If you have some ideas of how to do this cleanly suggestions/PRs are welcome.

**Comment by wenlock** [comment]
Cool, thanks for the info... might make that a weekend project if I get some time soon!

**Comment by YuriSolovyov** [comment]
This should be totally possible, though you would have to make N requests to N sources, not sure if GitHub allows you to aggregate that.

**Comment by sindresorhus** [comment]
Duplicate of #95
