### ISSUE TITLE
Notification count is undefined

### ISSUE THREAD

**Issue by vpArth** [sindresorhus/notifier-for-github#84]
![1](https://cloud.githubusercontent.com/assets/4529061/15348995/e5e6cf5a-1cf0-11e6-9800-dc481feb9fd6.png)

May be it's because githubAPI heartbeat is too often. It just reaches `GitHub API hourly limit`.

**Comment by dually8** [comment]
I am getting this, too.
![extensions](https://cloud.githubusercontent.com/assets/6304040/17216523/0a42534c-54af-11e6-9a32-ec9e03da9c07.png)

**Comment by Narno** [comment]
Some trouble for GitHub today: https://status.github.com/messages.

**Comment by jacobbearden** [comment]
@vpArth did this just end up being an issue with the API being down? or is it still a problem?

**Comment by vpArth** [comment]
@jacobbearden, 'm sorry, I removed this extension while it didn't work for me.
I think, it just was not care about possible other extensions using GithubAPI. (I use Octotree for example).

**Comment by shakeelmohamed** [comment]
I just saw this on Windows 10, created a new GitHub token and that fixed it instantly.

**Comment by sindresorhus** [comment]
We should have an error message telling people to add a token.

**Comment by notlmn** [comment]
The extension shows an `X` when there is no token!
