### ISSUE TITLE
Desktop notification option not saved when used on Firefox 48

### ISSUE THREAD

**Issue by xenithorb** [sindresorhus/notifier-for-github#86]
See here please: https://github.com/sindresorhus/notifier-for-github-firefox/issues/19

Title says it mostly.

**Comment by YurySolovyov** [comment]
As sindresorhus mentioned in the linked issue, FF 48 did not hit stable yet.
I might take a look when it comes out.

**Comment by xenithorb** [comment]
FF 53 has been stable for some time now. 57 is quickly approaching which is when people will be forced to use this extension over the deprecated one. 

This problem hasn't changed, still upon restart of the browser the desktop notification option is lost.
