### ISSUE TITLE
Support github.com and github enterprise at the same time

### ISSUE THREAD

**Issue by zaaack** [sindresorhus/notifier-for-github#95]
Please support github.com and github enterprise at the same time.

**Comment by shaleh** [comment]
What would the UX be?

Assuming we mash GH + GHE counts together into the badge, when you click it what happens?

Chrome (and others) do not allow two icons for one extension. I do not see a way to have multiple counts shown either.

I think we need to run two extensions, one for each. Yuck.

**Comment by YurySolovyov** [comment]
`<GH_COUNT>/<ENT_COUNT>` ? like: `3/14`

**Comment by shaleh** [comment]
What about the second problem? How do I see my GHE or my GH notifications?

**Comment by shaleh** [comment]
Also, we only get 4 chars so I hope you wipe out those notifications quickly :-)

**Comment by YurySolovyov** [comment]
Also, we can show combined number on badge, but on hover title, we can show them separate

**Comment by shaleh** [comment]
YurySolovyov, your class based refactor is a good starting place for this work. I was thinking that it could be extended a bit further to a Notifier class that wrapped most of the main logic. Then there could be two instances of that class say "primary" and "secondary" with their own Persistence beneath them for primaryRootUrl and the like and a "common" for the shared bits.

**Comment by zaaack** [comment]
Hi, I think two extension is fine for me, but all in one would be a better because I have too much extensions... I won't watchin
g  much repos, so there won't be

**Comment by sindresorhus** [comment]
I'm going to pass on this as it considerably complicates the code base and there's already too much code for us to properly maintain. The maintainers here also have no need for this feature.

**Comment by notlmn** [comment]
I'd like to redirect any angry mob users to https://github.com/sindresorhus/module-requests/issues/114 😉.
