### ISSUE TITLE
Do not show desktop notifications if I have the issue opened in one of my tabs

### ISSUE THREAD

**Issue by YurySolovyov** [sindresorhus/notifier-for-github#98]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/notifier-for-github/issues/98)

GitHub updates issues state in realtime-ish fashion, so no need to repeat it.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#194 not showing notification when tab is already opened](https://issuehunt.io/r/sindresorhus/notifier-for-github/pull/194)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/notifier-for-github/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by YurySolovyov** [comment]
Maybe not just block notifications in this case, but at least avoid reloading the page.

**Comment by sindresorhus** [comment]
👍 

---

> *Note: This issue has a bounty, so it's expected that you are an experienced programmer and that you give it your best effort. Don't forget, if applicable, to add tests, docs (double-check for typos), and update TypeScript definitions. Instead of asking too many questions, present solutions. The point of an issue bounty is to reduce my workload, not give me more. Thanks for helping out 🙌*

**Comment by notlmn** [comment]
Limitations explained in https://github.com/sindresorhus/notifier-for-github/pull/194#discussion_r356634397.

**Comment by sindresorhus** [comment]
@dirathea I'm rewarding this even though the PR was not merged to encourage you to contribute more :)

**Comment by dirathea** [comment]
Wow thank you @sindresorhus 😄
