### ISSUE TITLE
Integrate with refined-github's unread notifications

### ISSUE THREAD

**Issue by vadimdemedes** [sindresorhus/notifier-for-github#99]
Would be great if this extension could take into account unread notifications marked via refined-github extension. See https://github.com/sindresorhus/refined-github/pull/284.

**Comment by notlmn** [comment]
No longer possible because RGH uses its own extension storage to save notifications.

**Comment by YurySolovyov** [comment]
Why is that a problem? Do keys collide or something?

**Comment by notlmn** [comment]
No, because each extension has **its own** local `StorageArea` (`browser.storage.local`) that other extensions cannot access.
